//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ConstellationDashboardDailyReport
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ConstellationEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ConstellationEntities object using the connection string found in the 'ConstellationEntities' section of the application configuration file.
        /// </summary>
        public ConstellationEntities() : base("name=ConstellationEntities", "ConstellationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConstellationEntities object.
        /// </summary>
        public ConstellationEntities(string connectionString) : base(connectionString, "ConstellationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ConstellationEntities object.
        /// </summary>
        public ConstellationEntities(EntityConnection connection) : base(connection, "ConstellationEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblMain> tblMains
        {
            get
            {
                if ((_tblMains == null))
                {
                    _tblMains = base.CreateObjectSet<tblMain>("tblMains");
                }
                return _tblMains;
            }
        }
        private ObjectSet<tblMain> _tblMains;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblVendor> tblVendors
        {
            get
            {
                if ((_tblVendors == null))
                {
                    _tblVendors = base.CreateObjectSet<tblVendor>("tblVendors");
                }
                return _tblVendors;
            }
        }
        private ObjectSet<tblVendor> _tblVendors;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblMains EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblMains(tblMain tblMain)
        {
            base.AddObject("tblMains", tblMain);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblVendors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblVendors(tblVendor tblVendor)
        {
            base.AddObject("tblVendors", tblVendor);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConstellationModel", Name="tblMain")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblMain : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblMain object.
        /// </summary>
        /// <param name="mainId">Initial value of the MainId property.</param>
        public static tblMain CreatetblMain(global::System.Int32 mainId)
        {
            tblMain tblMain = new tblMain();
            tblMain.MainId = mainId;
            return tblMain;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MainId
        {
            get
            {
                return _MainId;
            }
            set
            {
                if (_MainId != value)
                {
                    OnMainIdChanging(value);
                    ReportPropertyChanging("MainId");
                    _MainId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MainId");
                    OnMainIdChanged();
                }
            }
        }
        private global::System.Int32 _MainId;
        partial void OnMainIdChanging(global::System.Int32 value);
        partial void OnMainIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CallDateTime
        {
            get
            {
                return _CallDateTime;
            }
            set
            {
                OnCallDateTimeChanging(value);
                ReportPropertyChanging("CallDateTime");
                _CallDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CallDateTime");
                OnCallDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CallDateTime;
        partial void OnCallDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCallDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WavName
        {
            get
            {
                return _WavName;
            }
            set
            {
                OnWavNameChanging(value);
                ReportPropertyChanging("WavName");
                _WavName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WavName");
                OnWavNameChanged();
            }
        }
        private global::System.String _WavName;
        partial void OnWavNameChanging(global::System.String value);
        partial void OnWavNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dnis
        {
            get
            {
                return _Dnis;
            }
            set
            {
                OnDnisChanging(value);
                ReportPropertyChanging("Dnis");
                _Dnis = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dnis");
                OnDnisChanged();
            }
        }
        private global::System.String _Dnis;
        partial void OnDnisChanging(global::System.String value);
        partial void OnDnisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Verified
        {
            get
            {
                return _Verified;
            }
            set
            {
                OnVerifiedChanging(value);
                ReportPropertyChanging("Verified");
                _Verified = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Verified");
                OnVerifiedChanged();
            }
        }
        private global::System.String _Verified;
        partial void OnVerifiedChanging(global::System.String value);
        partial void OnVerifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Concern
        {
            get
            {
                return _Concern;
            }
            set
            {
                OnConcernChanging(value);
                ReportPropertyChanging("Concern");
                _Concern = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Concern");
                OnConcernChanged();
            }
        }
        private global::System.String _Concern;
        partial void OnConcernChanging(global::System.String value);
        partial void OnConcernChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ConcernCode
        {
            get
            {
                return _ConcernCode;
            }
            set
            {
                OnConcernCodeChanging(value);
                ReportPropertyChanging("ConcernCode");
                _ConcernCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ConcernCode");
                OnConcernCodeChanged();
            }
        }
        private global::System.String _ConcernCode;
        partial void OnConcernCodeChanging(global::System.String value);
        partial void OnConcernCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TpvAgentName
        {
            get
            {
                return _TpvAgentName;
            }
            set
            {
                OnTpvAgentNameChanging(value);
                ReportPropertyChanging("TpvAgentName");
                _TpvAgentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TpvAgentName");
                OnTpvAgentNameChanged();
            }
        }
        private global::System.String _TpvAgentName;
        partial void OnTpvAgentNameChanging(global::System.String value);
        partial void OnTpvAgentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TpvAgentId
        {
            get
            {
                return _TpvAgentId;
            }
            set
            {
                OnTpvAgentIdChanging(value);
                ReportPropertyChanging("TpvAgentId");
                _TpvAgentId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TpvAgentId");
                OnTpvAgentIdChanged();
            }
        }
        private global::System.String _TpvAgentId;
        partial void OnTpvAgentIdChanging(global::System.String value);
        partial void OnTpvAgentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VendorId
        {
            get
            {
                return _VendorId;
            }
            set
            {
                OnVendorIdChanging(value);
                ReportPropertyChanging("VendorId");
                _VendorId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VendorId");
                OnVendorIdChanged();
            }
        }
        private global::System.String _VendorId;
        partial void OnVendorIdChanging(global::System.String value);
        partial void OnVendorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VendorAgentId
        {
            get
            {
                return _VendorAgentId;
            }
            set
            {
                OnVendorAgentIdChanging(value);
                ReportPropertyChanging("VendorAgentId");
                _VendorAgentId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VendorAgentId");
                OnVendorAgentIdChanged();
            }
        }
        private global::System.String _VendorAgentId;
        partial void OnVendorAgentIdChanging(global::System.String value);
        partial void OnVendorAgentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ResponseId
        {
            get
            {
                return _ResponseId;
            }
            set
            {
                OnResponseIdChanging(value);
                ReportPropertyChanging("ResponseId");
                _ResponseId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ResponseId");
                OnResponseIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ResponseId;
        partial void OnResponseIdChanging(Nullable<global::System.Int32> value);
        partial void OnResponseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SignUpType
        {
            get
            {
                return _SignUpType;
            }
            set
            {
                OnSignUpTypeChanging(value);
                ReportPropertyChanging("SignUpType");
                _SignUpType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SignUpType");
                OnSignUpTypeChanged();
            }
        }
        private global::System.String _SignUpType;
        partial void OnSignUpTypeChanging(global::System.String value);
        partial void OnSignUpTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceFirstName
        {
            get
            {
                return _ServiceFirstName;
            }
            set
            {
                OnServiceFirstNameChanging(value);
                ReportPropertyChanging("ServiceFirstName");
                _ServiceFirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceFirstName");
                OnServiceFirstNameChanged();
            }
        }
        private global::System.String _ServiceFirstName;
        partial void OnServiceFirstNameChanging(global::System.String value);
        partial void OnServiceFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceLastName
        {
            get
            {
                return _ServiceLastName;
            }
            set
            {
                OnServiceLastNameChanging(value);
                ReportPropertyChanging("ServiceLastName");
                _ServiceLastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceLastName");
                OnServiceLastNameChanged();
            }
        }
        private global::System.String _ServiceLastName;
        partial void OnServiceLastNameChanging(global::System.String value);
        partial void OnServiceLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceAddress1
        {
            get
            {
                return _ServiceAddress1;
            }
            set
            {
                OnServiceAddress1Changing(value);
                ReportPropertyChanging("ServiceAddress1");
                _ServiceAddress1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceAddress1");
                OnServiceAddress1Changed();
            }
        }
        private global::System.String _ServiceAddress1;
        partial void OnServiceAddress1Changing(global::System.String value);
        partial void OnServiceAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceAddress2
        {
            get
            {
                return _ServiceAddress2;
            }
            set
            {
                OnServiceAddress2Changing(value);
                ReportPropertyChanging("ServiceAddress2");
                _ServiceAddress2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceAddress2");
                OnServiceAddress2Changed();
            }
        }
        private global::System.String _ServiceAddress2;
        partial void OnServiceAddress2Changing(global::System.String value);
        partial void OnServiceAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceCity
        {
            get
            {
                return _ServiceCity;
            }
            set
            {
                OnServiceCityChanging(value);
                ReportPropertyChanging("ServiceCity");
                _ServiceCity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceCity");
                OnServiceCityChanged();
            }
        }
        private global::System.String _ServiceCity;
        partial void OnServiceCityChanging(global::System.String value);
        partial void OnServiceCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceCountry
        {
            get
            {
                return _ServiceCountry;
            }
            set
            {
                OnServiceCountryChanging(value);
                ReportPropertyChanging("ServiceCountry");
                _ServiceCountry = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceCountry");
                OnServiceCountryChanged();
            }
        }
        private global::System.String _ServiceCountry;
        partial void OnServiceCountryChanging(global::System.String value);
        partial void OnServiceCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceCounty
        {
            get
            {
                return _ServiceCounty;
            }
            set
            {
                OnServiceCountyChanging(value);
                ReportPropertyChanging("ServiceCounty");
                _ServiceCounty = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceCounty");
                OnServiceCountyChanged();
            }
        }
        private global::System.String _ServiceCounty;
        partial void OnServiceCountyChanging(global::System.String value);
        partial void OnServiceCountyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceState
        {
            get
            {
                return _ServiceState;
            }
            set
            {
                OnServiceStateChanging(value);
                ReportPropertyChanging("ServiceState");
                _ServiceState = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceState");
                OnServiceStateChanged();
            }
        }
        private global::System.String _ServiceState;
        partial void OnServiceStateChanging(global::System.String value);
        partial void OnServiceStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceZipCode
        {
            get
            {
                return _ServiceZipCode;
            }
            set
            {
                OnServiceZipCodeChanging(value);
                ReportPropertyChanging("ServiceZipCode");
                _ServiceZipCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceZipCode");
                OnServiceZipCodeChanged();
            }
        }
        private global::System.String _ServiceZipCode;
        partial void OnServiceZipCodeChanging(global::System.String value);
        partial void OnServiceZipCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServicePhoneNumber
        {
            get
            {
                return _ServicePhoneNumber;
            }
            set
            {
                OnServicePhoneNumberChanging(value);
                ReportPropertyChanging("ServicePhoneNumber");
                _ServicePhoneNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServicePhoneNumber");
                OnServicePhoneNumberChanged();
            }
        }
        private global::System.String _ServicePhoneNumber;
        partial void OnServicePhoneNumberChanging(global::System.String value);
        partial void OnServicePhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceEmail
        {
            get
            {
                return _ServiceEmail;
            }
            set
            {
                OnServiceEmailChanging(value);
                ReportPropertyChanging("ServiceEmail");
                _ServiceEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceEmail");
                OnServiceEmailChanged();
            }
        }
        private global::System.String _ServiceEmail;
        partial void OnServiceEmailChanging(global::System.String value);
        partial void OnServiceEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillingFirstName
        {
            get
            {
                return _BillingFirstName;
            }
            set
            {
                OnBillingFirstNameChanging(value);
                ReportPropertyChanging("BillingFirstName");
                _BillingFirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BillingFirstName");
                OnBillingFirstNameChanged();
            }
        }
        private global::System.String _BillingFirstName;
        partial void OnBillingFirstNameChanging(global::System.String value);
        partial void OnBillingFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillingLastName
        {
            get
            {
                return _BillingLastName;
            }
            set
            {
                OnBillingLastNameChanging(value);
                ReportPropertyChanging("BillingLastName");
                _BillingLastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BillingLastName");
                OnBillingLastNameChanged();
            }
        }
        private global::System.String _BillingLastName;
        partial void OnBillingLastNameChanging(global::System.String value);
        partial void OnBillingLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillingAddress1
        {
            get
            {
                return _BillingAddress1;
            }
            set
            {
                OnBillingAddress1Changing(value);
                ReportPropertyChanging("BillingAddress1");
                _BillingAddress1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BillingAddress1");
                OnBillingAddress1Changed();
            }
        }
        private global::System.String _BillingAddress1;
        partial void OnBillingAddress1Changing(global::System.String value);
        partial void OnBillingAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillingAddress2
        {
            get
            {
                return _BillingAddress2;
            }
            set
            {
                OnBillingAddress2Changing(value);
                ReportPropertyChanging("BillingAddress2");
                _BillingAddress2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BillingAddress2");
                OnBillingAddress2Changed();
            }
        }
        private global::System.String _BillingAddress2;
        partial void OnBillingAddress2Changing(global::System.String value);
        partial void OnBillingAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillingCity
        {
            get
            {
                return _BillingCity;
            }
            set
            {
                OnBillingCityChanging(value);
                ReportPropertyChanging("BillingCity");
                _BillingCity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BillingCity");
                OnBillingCityChanged();
            }
        }
        private global::System.String _BillingCity;
        partial void OnBillingCityChanging(global::System.String value);
        partial void OnBillingCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillingCountry
        {
            get
            {
                return _BillingCountry;
            }
            set
            {
                OnBillingCountryChanging(value);
                ReportPropertyChanging("BillingCountry");
                _BillingCountry = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BillingCountry");
                OnBillingCountryChanged();
            }
        }
        private global::System.String _BillingCountry;
        partial void OnBillingCountryChanging(global::System.String value);
        partial void OnBillingCountryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillingCounty
        {
            get
            {
                return _BillingCounty;
            }
            set
            {
                OnBillingCountyChanging(value);
                ReportPropertyChanging("BillingCounty");
                _BillingCounty = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BillingCounty");
                OnBillingCountyChanged();
            }
        }
        private global::System.String _BillingCounty;
        partial void OnBillingCountyChanging(global::System.String value);
        partial void OnBillingCountyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillingState
        {
            get
            {
                return _BillingState;
            }
            set
            {
                OnBillingStateChanging(value);
                ReportPropertyChanging("BillingState");
                _BillingState = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BillingState");
                OnBillingStateChanged();
            }
        }
        private global::System.String _BillingState;
        partial void OnBillingStateChanging(global::System.String value);
        partial void OnBillingStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillingZipCode
        {
            get
            {
                return _BillingZipCode;
            }
            set
            {
                OnBillingZipCodeChanging(value);
                ReportPropertyChanging("BillingZipCode");
                _BillingZipCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BillingZipCode");
                OnBillingZipCodeChanged();
            }
        }
        private global::System.String _BillingZipCode;
        partial void OnBillingZipCodeChanging(global::System.String value);
        partial void OnBillingZipCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BillingEmail
        {
            get
            {
                return _BillingEmail;
            }
            set
            {
                OnBillingEmailChanging(value);
                ReportPropertyChanging("BillingEmail");
                _BillingEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BillingEmail");
                OnBillingEmailChanged();
            }
        }
        private global::System.String _BillingEmail;
        partial void OnBillingEmailChanging(global::System.String value);
        partial void OnBillingEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UDCCode
        {
            get
            {
                return _UDCCode;
            }
            set
            {
                OnUDCCodeChanging(value);
                ReportPropertyChanging("UDCCode");
                _UDCCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UDCCode");
                OnUDCCodeChanged();
            }
        }
        private global::System.String _UDCCode;
        partial void OnUDCCodeChanging(global::System.String value);
        partial void OnUDCCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UDCAccountNumber
        {
            get
            {
                return _UDCAccountNumber;
            }
            set
            {
                OnUDCAccountNumberChanging(value);
                ReportPropertyChanging("UDCAccountNumber");
                _UDCAccountNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UDCAccountNumber");
                OnUDCAccountNumberChanged();
            }
        }
        private global::System.String _UDCAccountNumber;
        partial void OnUDCAccountNumberChanging(global::System.String value);
        partial void OnUDCAccountNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GasUDCCode
        {
            get
            {
                return _GasUDCCode;
            }
            set
            {
                OnGasUDCCodeChanging(value);
                ReportPropertyChanging("GasUDCCode");
                _GasUDCCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GasUDCCode");
                OnGasUDCCodeChanged();
            }
        }
        private global::System.String _GasUDCCode;
        partial void OnGasUDCCodeChanging(global::System.String value);
        partial void OnGasUDCCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GasUDCAccountNumber
        {
            get
            {
                return _GasUDCAccountNumber;
            }
            set
            {
                OnGasUDCAccountNumberChanging(value);
                ReportPropertyChanging("GasUDCAccountNumber");
                _GasUDCAccountNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GasUDCAccountNumber");
                OnGasUDCAccountNumberChanged();
            }
        }
        private global::System.String _GasUDCAccountNumber;
        partial void OnGasUDCAccountNumberChanging(global::System.String value);
        partial void OnGasUDCAccountNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FixedEnergyPrice
        {
            get
            {
                return _FixedEnergyPrice;
            }
            set
            {
                OnFixedEnergyPriceChanging(value);
                ReportPropertyChanging("FixedEnergyPrice");
                _FixedEnergyPrice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FixedEnergyPrice");
                OnFixedEnergyPriceChanged();
            }
        }
        private global::System.String _FixedEnergyPrice;
        partial void OnFixedEnergyPriceChanging(global::System.String value);
        partial void OnFixedEnergyPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KWH2000Price
        {
            get
            {
                return _KWH2000Price;
            }
            set
            {
                OnKWH2000PriceChanging(value);
                ReportPropertyChanging("KWH2000Price");
                _KWH2000Price = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KWH2000Price");
                OnKWH2000PriceChanged();
            }
        }
        private global::System.String _KWH2000Price;
        partial void OnKWH2000PriceChanging(global::System.String value);
        partial void OnKWH2000PriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MinimumUsageFee
        {
            get
            {
                return _MinimumUsageFee;
            }
            set
            {
                OnMinimumUsageFeeChanging(value);
                ReportPropertyChanging("MinimumUsageFee");
                _MinimumUsageFee = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MinimumUsageFee");
                OnMinimumUsageFeeChanged();
            }
        }
        private global::System.String _MinimumUsageFee;
        partial void OnMinimumUsageFeeChanging(global::System.String value);
        partial void OnMinimumUsageFeeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MinimumUsageThreshold
        {
            get
            {
                return _MinimumUsageThreshold;
            }
            set
            {
                OnMinimumUsageThresholdChanging(value);
                ReportPropertyChanging("MinimumUsageThreshold");
                _MinimumUsageThreshold = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MinimumUsageThreshold");
                OnMinimumUsageThresholdChanged();
            }
        }
        private global::System.String _MinimumUsageThreshold;
        partial void OnMinimumUsageThresholdChanging(global::System.String value);
        partial void OnMinimumUsageThresholdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ElectricTerm
        {
            get
            {
                return _ElectricTerm;
            }
            set
            {
                OnElectricTermChanging(value);
                ReportPropertyChanging("ElectricTerm");
                _ElectricTerm = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ElectricTerm");
                OnElectricTermChanged();
            }
        }
        private global::System.String _ElectricTerm;
        partial void OnElectricTermChanging(global::System.String value);
        partial void OnElectricTermChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ElectricPrice
        {
            get
            {
                return _ElectricPrice;
            }
            set
            {
                OnElectricPriceChanging(value);
                ReportPropertyChanging("ElectricPrice");
                _ElectricPrice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ElectricPrice");
                OnElectricPriceChanged();
            }
        }
        private global::System.String _ElectricPrice;
        partial void OnElectricPriceChanging(global::System.String value);
        partial void OnElectricPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ElectricCancelFee
        {
            get
            {
                return _ElectricCancelFee;
            }
            set
            {
                OnElectricCancelFeeChanging(value);
                ReportPropertyChanging("ElectricCancelFee");
                _ElectricCancelFee = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ElectricCancelFee");
                OnElectricCancelFeeChanged();
            }
        }
        private global::System.String _ElectricCancelFee;
        partial void OnElectricCancelFeeChanging(global::System.String value);
        partial void OnElectricCancelFeeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ElectricPlanName
        {
            get
            {
                return _ElectricPlanName;
            }
            set
            {
                OnElectricPlanNameChanging(value);
                ReportPropertyChanging("ElectricPlanName");
                _ElectricPlanName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ElectricPlanName");
                OnElectricPlanNameChanged();
            }
        }
        private global::System.String _ElectricPlanName;
        partial void OnElectricPlanNameChanging(global::System.String value);
        partial void OnElectricPlanNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GasTerm
        {
            get
            {
                return _GasTerm;
            }
            set
            {
                OnGasTermChanging(value);
                ReportPropertyChanging("GasTerm");
                _GasTerm = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GasTerm");
                OnGasTermChanged();
            }
        }
        private global::System.String _GasTerm;
        partial void OnGasTermChanging(global::System.String value);
        partial void OnGasTermChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GasPrice
        {
            get
            {
                return _GasPrice;
            }
            set
            {
                OnGasPriceChanging(value);
                ReportPropertyChanging("GasPrice");
                _GasPrice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GasPrice");
                OnGasPriceChanged();
            }
        }
        private global::System.String _GasPrice;
        partial void OnGasPriceChanging(global::System.String value);
        partial void OnGasPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GasCancelFee
        {
            get
            {
                return _GasCancelFee;
            }
            set
            {
                OnGasCancelFeeChanging(value);
                ReportPropertyChanging("GasCancelFee");
                _GasCancelFee = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GasCancelFee");
                OnGasCancelFeeChanged();
            }
        }
        private global::System.String _GasCancelFee;
        partial void OnGasCancelFeeChanging(global::System.String value);
        partial void OnGasCancelFeeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MeterNumber
        {
            get
            {
                return _MeterNumber;
            }
            set
            {
                OnMeterNumberChanging(value);
                ReportPropertyChanging("MeterNumber");
                _MeterNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MeterNumber");
                OnMeterNumberChanged();
            }
        }
        private global::System.String _MeterNumber;
        partial void OnMeterNumberChanging(global::System.String value);
        partial void OnMeterNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EmailNeedsUpdate
        {
            get
            {
                return _EmailNeedsUpdate;
            }
            set
            {
                OnEmailNeedsUpdateChanging(value);
                ReportPropertyChanging("EmailNeedsUpdate");
                _EmailNeedsUpdate = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EmailNeedsUpdate");
                OnEmailNeedsUpdateChanged();
            }
        }
        private global::System.String _EmailNeedsUpdate;
        partial void OnEmailNeedsUpdateChanging(global::System.String value);
        partial void OnEmailNeedsUpdateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UpdatedServiceEmail
        {
            get
            {
                return _UpdatedServiceEmail;
            }
            set
            {
                OnUpdatedServiceEmailChanging(value);
                ReportPropertyChanging("UpdatedServiceEmail");
                _UpdatedServiceEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UpdatedServiceEmail");
                OnUpdatedServiceEmailChanged();
            }
        }
        private global::System.String _UpdatedServiceEmail;
        partial void OnUpdatedServiceEmailChanging(global::System.String value);
        partial void OnUpdatedServiceEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tblAgentKeyId
        {
            get
            {
                return _tblAgentKeyId;
            }
            set
            {
                OntblAgentKeyIdChanging(value);
                ReportPropertyChanging("tblAgentKeyId");
                _tblAgentKeyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tblAgentKeyId");
                OntblAgentKeyIdChanged();
            }
        }
        private Nullable<global::System.Int32> _tblAgentKeyId;
        partial void OntblAgentKeyIdChanging(Nullable<global::System.Int32> value);
        partial void OntblAgentKeyIdChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ConstellationModel", Name="tblVendor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblVendor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblVendor object.
        /// </summary>
        /// <param name="vendorId">Initial value of the VendorId property.</param>
        public static tblVendor CreatetblVendor(global::System.Int32 vendorId)
        {
            tblVendor tblVendor = new tblVendor();
            tblVendor.VendorId = vendorId;
            return tblVendor;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VendorId
        {
            get
            {
                return _VendorId;
            }
            set
            {
                if (_VendorId != value)
                {
                    OnVendorIdChanging(value);
                    ReportPropertyChanging("VendorId");
                    _VendorId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VendorId");
                    OnVendorIdChanged();
                }
            }
        }
        private global::System.Int32 _VendorId;
        partial void OnVendorIdChanging(global::System.Int32 value);
        partial void OnVendorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String VendorName
        {
            get
            {
                return _VendorName;
            }
            set
            {
                OnVendorNameChanging(value);
                ReportPropertyChanging("VendorName");
                _VendorName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("VendorName");
                OnVendorNameChanged();
            }
        }
        private global::System.String _VendorName;
        partial void OnVendorNameChanging(global::System.String value);
        partial void OnVendorNameChanged();

        #endregion

    
    }

    #endregion

    
}
