//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SparkWsTest.SparkWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SparkWSSoap", Namespace="https://wsssl.calibrus.com/Spark/")]
    public partial class SparkWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SubmitRecordOperationCompleted;
        
        private System.Threading.SendOrPostCallback RetrieveRecordOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SparkWS() {
            this.Url = global::SparkWsTest.Properties.Settings.Default.SparkWsTest_SparkWS_SparkWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SubmitRecordCompletedEventHandler SubmitRecordCompleted;
        
        /// <remarks/>
        public event RetrieveRecordCompletedEventHandler RetrieveRecordCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://wsssl.calibrus.com/Spark/SubmitInformation", RequestElementName="SubmitInformation", RequestNamespace="https://wsssl.calibrus.com/Spark/", ResponseElementName="SubmitInformationResponse", ResponseNamespace="https://wsssl.calibrus.com/Spark/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("SubmitInformationResult")]
        public string SubmitRecord(Record record) {
            object[] results = this.Invoke("SubmitRecord", new object[] {
                        record});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SubmitRecordAsync(Record record) {
            this.SubmitRecordAsync(record, null);
        }
        
        /// <remarks/>
        public void SubmitRecordAsync(Record record, object userState) {
            if ((this.SubmitRecordOperationCompleted == null)) {
                this.SubmitRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubmitRecordOperationCompleted);
            }
            this.InvokeAsync("SubmitRecord", new object[] {
                        record}, this.SubmitRecordOperationCompleted, userState);
        }
        
        private void OnSubmitRecordOperationCompleted(object arg) {
            if ((this.SubmitRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubmitRecordCompleted(this, new SubmitRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://wsssl.calibrus.com/Spark/RetrieveRecords", RequestElementName="RetrieveRecords", RequestNamespace="https://wsssl.calibrus.com/Spark/", ResponseElementName="RetrieveRecordsResponse", ResponseNamespace="https://wsssl.calibrus.com/Spark/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("RetrieveRecordsResult")]
        public TPVRecord[] RetrieveRecord(string StartDate, string EndDate, string VendorNumber) {
            object[] results = this.Invoke("RetrieveRecord", new object[] {
                        StartDate,
                        EndDate,
                        VendorNumber});
            return ((TPVRecord[])(results[0]));
        }
        
        /// <remarks/>
        public void RetrieveRecordAsync(string StartDate, string EndDate, string VendorNumber) {
            this.RetrieveRecordAsync(StartDate, EndDate, VendorNumber, null);
        }
        
        /// <remarks/>
        public void RetrieveRecordAsync(string StartDate, string EndDate, string VendorNumber, object userState) {
            if ((this.RetrieveRecordOperationCompleted == null)) {
                this.RetrieveRecordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRetrieveRecordOperationCompleted);
            }
            this.InvokeAsync("RetrieveRecord", new object[] {
                        StartDate,
                        EndDate,
                        VendorNumber}, this.RetrieveRecordOperationCompleted, userState);
        }
        
        private void OnRetrieveRecordOperationCompleted(object arg) {
            if ((this.RetrieveRecordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RetrieveRecordCompleted(this, new RetrieveRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://wsssl.calibrus.com/Spark/")]
    public partial class Record {
        
        private string agentIdField;
        
        private string vendorNumberField;
        
        private string emailField;
        
        private string recordLocatorField;
        
        private string salesStateField;
        
        private string authorizationFirstNameField;
        
        private string authorizationMiddleField;
        
        private string authorizationLastNameField;
        
        private string btnField;
        
        private string companyNameField;
        
        private string companyContactFirstNameField;
        
        private string companyContactLastNameField;
        
        private string companyContactTitleField;
        
        private string territoryField;
        
        private string leadTypeField;
        
        private string relationField;
        
        private string numberOfAccountsField;
        
        private string accountFirstNameField;
        
        private string accountLastNameField;
        
        private RecordDetail[] recordDetailsField;
        
        /// <remarks/>
        public string AgentId {
            get {
                return this.agentIdField;
            }
            set {
                this.agentIdField = value;
            }
        }
        
        /// <remarks/>
        public string VendorNumber {
            get {
                return this.vendorNumberField;
            }
            set {
                this.vendorNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string RecordLocator {
            get {
                return this.recordLocatorField;
            }
            set {
                this.recordLocatorField = value;
            }
        }
        
        /// <remarks/>
        public string SalesState {
            get {
                return this.salesStateField;
            }
            set {
                this.salesStateField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorizationFirstName {
            get {
                return this.authorizationFirstNameField;
            }
            set {
                this.authorizationFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorizationMiddle {
            get {
                return this.authorizationMiddleField;
            }
            set {
                this.authorizationMiddleField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorizationLastName {
            get {
                return this.authorizationLastNameField;
            }
            set {
                this.authorizationLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Btn {
            get {
                return this.btnField;
            }
            set {
                this.btnField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyContactFirstName {
            get {
                return this.companyContactFirstNameField;
            }
            set {
                this.companyContactFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyContactLastName {
            get {
                return this.companyContactLastNameField;
            }
            set {
                this.companyContactLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyContactTitle {
            get {
                return this.companyContactTitleField;
            }
            set {
                this.companyContactTitleField = value;
            }
        }
        
        /// <remarks/>
        public string Territory {
            get {
                return this.territoryField;
            }
            set {
                this.territoryField = value;
            }
        }
        
        /// <remarks/>
        public string LeadType {
            get {
                return this.leadTypeField;
            }
            set {
                this.leadTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Relation {
            get {
                return this.relationField;
            }
            set {
                this.relationField = value;
            }
        }
        
        /// <remarks/>
        public string NumberOfAccounts {
            get {
                return this.numberOfAccountsField;
            }
            set {
                this.numberOfAccountsField = value;
            }
        }
        
        /// <remarks/>
        public string AccountFirstName {
            get {
                return this.accountFirstNameField;
            }
            set {
                this.accountFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string AccountLastName {
            get {
                return this.accountLastNameField;
            }
            set {
                this.accountLastNameField = value;
            }
        }
        
        /// <remarks/>
        public RecordDetail[] RecordDetails {
            get {
                return this.recordDetailsField;
            }
            set {
                this.recordDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://wsssl.calibrus.com/Spark/")]
    public partial class RecordDetail {
        
        private string programCodeField;
        
        private string utilityTypeField;
        
        private string accountTypeField;
        
        private string accountNumberField;
        
        private string meterNumberField;
        
        private string rateClassField;
        
        private string customerNameKeyField;
        
        private string serviceReferenceNumberField;
        
        private string serviceAddressField;
        
        private string serviceCityField;
        
        private string serviceStateField;
        
        private string serviceZipField;
        
        private string billingAddressField;
        
        private string billingCityField;
        
        private string billingStateField;
        
        private string billingZipField;
        
        private string inCityLimitsField;
        
        private string billingFirstNameField;
        
        private string billingLastNameField;
        
        /// <remarks/>
        public string ProgramCode {
            get {
                return this.programCodeField;
            }
            set {
                this.programCodeField = value;
            }
        }
        
        /// <remarks/>
        public string UtilityType {
            get {
                return this.utilityTypeField;
            }
            set {
                this.utilityTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AccountType {
            get {
                return this.accountTypeField;
            }
            set {
                this.accountTypeField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string MeterNumber {
            get {
                return this.meterNumberField;
            }
            set {
                this.meterNumberField = value;
            }
        }
        
        /// <remarks/>
        public string RateClass {
            get {
                return this.rateClassField;
            }
            set {
                this.rateClassField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerNameKey {
            get {
                return this.customerNameKeyField;
            }
            set {
                this.customerNameKeyField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceReferenceNumber {
            get {
                return this.serviceReferenceNumberField;
            }
            set {
                this.serviceReferenceNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceAddress {
            get {
                return this.serviceAddressField;
            }
            set {
                this.serviceAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceCity {
            get {
                return this.serviceCityField;
            }
            set {
                this.serviceCityField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceState {
            get {
                return this.serviceStateField;
            }
            set {
                this.serviceStateField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceZip {
            get {
                return this.serviceZipField;
            }
            set {
                this.serviceZipField = value;
            }
        }
        
        /// <remarks/>
        public string BillingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
            }
        }
        
        /// <remarks/>
        public string BillingCity {
            get {
                return this.billingCityField;
            }
            set {
                this.billingCityField = value;
            }
        }
        
        /// <remarks/>
        public string BillingState {
            get {
                return this.billingStateField;
            }
            set {
                this.billingStateField = value;
            }
        }
        
        /// <remarks/>
        public string BillingZip {
            get {
                return this.billingZipField;
            }
            set {
                this.billingZipField = value;
            }
        }
        
        /// <remarks/>
        public string InCityLimits {
            get {
                return this.inCityLimitsField;
            }
            set {
                this.inCityLimitsField = value;
            }
        }
        
        /// <remarks/>
        public string BillingFirstName {
            get {
                return this.billingFirstNameField;
            }
            set {
                this.billingFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string BillingLastName {
            get {
                return this.billingLastNameField;
            }
            set {
                this.billingLastNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://wsssl.calibrus.com/Spark/")]
    public partial class TPVRecord {
        
        private int calibrusRecordLocatorField;
        
        private System.Nullable<System.DateTime> callDateTimeField;
        
        private System.Nullable<System.DateTime> webDateTimeField;
        
        private string verifiedField;
        
        private string concernField;
        
        private string concernCodeField;
        
        private string tpvAgentNameField;
        
        private string tpvAgentIdField;
        
        private string agentIDField;
        
        private string agentFirstNameField;
        
        private string agentLastNameField;
        
        private string emailField;
        
        private string authorizationFirstNameField;
        
        private string authorizationLastNameField;
        
        private string accountFirstNameField;
        
        private string accountLastNameField;
        
        private string relationField;
        
        private string btnField;
        
        private string accountNumberField;
        
        private string customerNameKeyField;
        
        private string serviceAddressField;
        
        private string serviceCityField;
        
        private string serviceCountyField;
        
        private string serviceStateField;
        
        private string serviceZipField;
        
        private string billingAddressField;
        
        private string billingCityField;
        
        private string billingCountyField;
        
        private string billingStateField;
        
        private string billingZipField;
        
        private string programCodeField;
        
        private string programNameField;
        
        private System.Nullable<decimal> mSFField;
        
        private System.Nullable<decimal> eTFField;
        
        private System.Nullable<decimal> rateField;
        
        private System.Nullable<decimal> termField;
        
        private string utilityTypeField;
        
        private string premiseTypeField;
        
        private string stateField;
        
        private string ldcCodeField;
        
        private string accountNumberTypeField;
        
        private string billingFirstNameField;
        
        private string billingLastNameField;
        
        /// <remarks/>
        public int CalibrusRecordLocator {
            get {
                return this.calibrusRecordLocatorField;
            }
            set {
                this.calibrusRecordLocatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CallDateTime {
            get {
                return this.callDateTimeField;
            }
            set {
                this.callDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> WebDateTime {
            get {
                return this.webDateTimeField;
            }
            set {
                this.webDateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string Verified {
            get {
                return this.verifiedField;
            }
            set {
                this.verifiedField = value;
            }
        }
        
        /// <remarks/>
        public string Concern {
            get {
                return this.concernField;
            }
            set {
                this.concernField = value;
            }
        }
        
        /// <remarks/>
        public string ConcernCode {
            get {
                return this.concernCodeField;
            }
            set {
                this.concernCodeField = value;
            }
        }
        
        /// <remarks/>
        public string TpvAgentName {
            get {
                return this.tpvAgentNameField;
            }
            set {
                this.tpvAgentNameField = value;
            }
        }
        
        /// <remarks/>
        public string TpvAgentId {
            get {
                return this.tpvAgentIdField;
            }
            set {
                this.tpvAgentIdField = value;
            }
        }
        
        /// <remarks/>
        public string AgentID {
            get {
                return this.agentIDField;
            }
            set {
                this.agentIDField = value;
            }
        }
        
        /// <remarks/>
        public string AgentFirstName {
            get {
                return this.agentFirstNameField;
            }
            set {
                this.agentFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string AgentLastName {
            get {
                return this.agentLastNameField;
            }
            set {
                this.agentLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorizationFirstName {
            get {
                return this.authorizationFirstNameField;
            }
            set {
                this.authorizationFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string AuthorizationLastName {
            get {
                return this.authorizationLastNameField;
            }
            set {
                this.authorizationLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string AccountFirstName {
            get {
                return this.accountFirstNameField;
            }
            set {
                this.accountFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string AccountLastName {
            get {
                return this.accountLastNameField;
            }
            set {
                this.accountLastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Relation {
            get {
                return this.relationField;
            }
            set {
                this.relationField = value;
            }
        }
        
        /// <remarks/>
        public string Btn {
            get {
                return this.btnField;
            }
            set {
                this.btnField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerNameKey {
            get {
                return this.customerNameKeyField;
            }
            set {
                this.customerNameKeyField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceAddress {
            get {
                return this.serviceAddressField;
            }
            set {
                this.serviceAddressField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceCity {
            get {
                return this.serviceCityField;
            }
            set {
                this.serviceCityField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceCounty {
            get {
                return this.serviceCountyField;
            }
            set {
                this.serviceCountyField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceState {
            get {
                return this.serviceStateField;
            }
            set {
                this.serviceStateField = value;
            }
        }
        
        /// <remarks/>
        public string ServiceZip {
            get {
                return this.serviceZipField;
            }
            set {
                this.serviceZipField = value;
            }
        }
        
        /// <remarks/>
        public string BillingAddress {
            get {
                return this.billingAddressField;
            }
            set {
                this.billingAddressField = value;
            }
        }
        
        /// <remarks/>
        public string BillingCity {
            get {
                return this.billingCityField;
            }
            set {
                this.billingCityField = value;
            }
        }
        
        /// <remarks/>
        public string BillingCounty {
            get {
                return this.billingCountyField;
            }
            set {
                this.billingCountyField = value;
            }
        }
        
        /// <remarks/>
        public string BillingState {
            get {
                return this.billingStateField;
            }
            set {
                this.billingStateField = value;
            }
        }
        
        /// <remarks/>
        public string BillingZip {
            get {
                return this.billingZipField;
            }
            set {
                this.billingZipField = value;
            }
        }
        
        /// <remarks/>
        public string ProgramCode {
            get {
                return this.programCodeField;
            }
            set {
                this.programCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ProgramName {
            get {
                return this.programNameField;
            }
            set {
                this.programNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> MSF {
            get {
                return this.mSFField;
            }
            set {
                this.mSFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ETF {
            get {
                return this.eTFField;
            }
            set {
                this.eTFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Rate {
            get {
                return this.rateField;
            }
            set {
                this.rateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> Term {
            get {
                return this.termField;
            }
            set {
                this.termField = value;
            }
        }
        
        /// <remarks/>
        public string UtilityType {
            get {
                return this.utilityTypeField;
            }
            set {
                this.utilityTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PremiseType {
            get {
                return this.premiseTypeField;
            }
            set {
                this.premiseTypeField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string LdcCode {
            get {
                return this.ldcCodeField;
            }
            set {
                this.ldcCodeField = value;
            }
        }
        
        /// <remarks/>
        public string AccountNumberType {
            get {
                return this.accountNumberTypeField;
            }
            set {
                this.accountNumberTypeField = value;
            }
        }
        
        /// <remarks/>
        public string BillingFirstName {
            get {
                return this.billingFirstNameField;
            }
            set {
                this.billingFirstNameField = value;
            }
        }
        
        /// <remarks/>
        public string BillingLastName {
            get {
                return this.billingLastNameField;
            }
            set {
                this.billingLastNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void SubmitRecordCompletedEventHandler(object sender, SubmitRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubmitRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubmitRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void RetrieveRecordCompletedEventHandler(object sender, RetrieveRecordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetrieveRecordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RetrieveRecordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TPVRecord[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TPVRecord[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591