//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CalibrusModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CalibrusEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CalibrusEntities object using the connection string found in the 'CalibrusEntities' section of the application configuration file.
        /// </summary>
        public CalibrusEntities() : base("name=CalibrusEntities", "CalibrusEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CalibrusEntities object.
        /// </summary>
        public CalibrusEntities(string connectionString) : base(connectionString, "CalibrusEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CalibrusEntities object.
        /// </summary>
        public CalibrusEntities(EntityConnection connection) : base(connection, "CalibrusEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblOnlineFeedbackForm> tblOnlineFeedbackForms
        {
            get
            {
                if ((_tblOnlineFeedbackForms == null))
                {
                    _tblOnlineFeedbackForms = base.CreateObjectSet<tblOnlineFeedbackForm>("tblOnlineFeedbackForms");
                }
                return _tblOnlineFeedbackForms;
            }
        }
        private ObjectSet<tblOnlineFeedbackForm> _tblOnlineFeedbackForms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblState> tblStates
        {
            get
            {
                if ((_tblStates == null))
                {
                    _tblStates = base.CreateObjectSet<tblState>("tblStates");
                }
                return _tblStates;
            }
        }
        private ObjectSet<tblState> _tblStates;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblOnlineFeedbackForms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblOnlineFeedbackForms(tblOnlineFeedbackForm tblOnlineFeedbackForm)
        {
            base.AddObject("tblOnlineFeedbackForms", tblOnlineFeedbackForm);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblStates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblStates(tblState tblState)
        {
            base.AddObject("tblStates", tblState);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CalibrusModel", Name="tblOnlineFeedbackForm")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblOnlineFeedbackForm : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblOnlineFeedbackForm object.
        /// </summary>
        /// <param name="mainId">Initial value of the MainId property.</param>
        public static tblOnlineFeedbackForm CreatetblOnlineFeedbackForm(global::System.Int32 mainId)
        {
            tblOnlineFeedbackForm tblOnlineFeedbackForm = new tblOnlineFeedbackForm();
            tblOnlineFeedbackForm.MainId = mainId;
            return tblOnlineFeedbackForm;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MainId
        {
            get
            {
                return _MainId;
            }
            set
            {
                if (_MainId != value)
                {
                    OnMainIdChanging(value);
                    ReportPropertyChanging("MainId");
                    _MainId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MainId");
                    OnMainIdChanged();
                }
            }
        }
        private global::System.Int32 _MainId;
        partial void OnMainIdChanging(global::System.Int32 value);
        partial void OnMainIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> WebDateTime
        {
            get
            {
                return _WebDateTime;
            }
            set
            {
                OnWebDateTimeChanging(value);
                ReportPropertyChanging("WebDateTime");
                _WebDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WebDateTime");
                OnWebDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _WebDateTime;
        partial void OnWebDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnWebDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Company
        {
            get
            {
                return _Company;
            }
            set
            {
                OnCompanyChanging(value);
                ReportPropertyChanging("Company");
                _Company = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Company");
                OnCompanyChanged();
            }
        }
        private global::System.String _Company;
        partial void OnCompanyChanging(global::System.String value);
        partial void OnCompanyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StateAbbrev
        {
            get
            {
                return _StateAbbrev;
            }
            set
            {
                OnStateAbbrevChanging(value);
                ReportPropertyChanging("StateAbbrev");
                _StateAbbrev = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StateAbbrev");
                OnStateAbbrevChanged();
            }
        }
        private global::System.String _StateAbbrev;
        partial void OnStateAbbrevChanging(global::System.String value);
        partial void OnStateAbbrevChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CalibrusModel", Name="tblState")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblState : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblState object.
        /// </summary>
        /// <param name="stateAbbr">Initial value of the StateAbbr property.</param>
        /// <param name="stateName">Initial value of the StateName property.</param>
        public static tblState CreatetblState(global::System.String stateAbbr, global::System.String stateName)
        {
            tblState tblState = new tblState();
            tblState.StateAbbr = stateAbbr;
            tblState.StateName = stateName;
            return tblState;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StateAbbr
        {
            get
            {
                return _StateAbbr;
            }
            set
            {
                if (_StateAbbr != value)
                {
                    OnStateAbbrChanging(value);
                    ReportPropertyChanging("StateAbbr");
                    _StateAbbr = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("StateAbbr");
                    OnStateAbbrChanged();
                }
            }
        }
        private global::System.String _StateAbbr;
        partial void OnStateAbbrChanging(global::System.String value);
        partial void OnStateAbbrChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String StateName
        {
            get
            {
                return _StateName;
            }
            set
            {
                if (_StateName != value)
                {
                    OnStateNameChanging(value);
                    ReportPropertyChanging("StateName");
                    _StateName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("StateName");
                    OnStateNameChanged();
                }
            }
        }
        private global::System.String _StateName;
        partial void OnStateNameChanging(global::System.String value);
        partial void OnStateNameChanged();

        #endregion

    
    }

    #endregion

    
}
