// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5

using Newtonsoft.Json;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CalibrusTPV.ReversePocoGen
{

    // Directives
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class Directive
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public string Tag { get; set; } // Tag (length: 50)
        public string Description { get; set; } // Description (length: 250)

        // Reverse navigation
        [JsonIgnore]
        public virtual System.Collections.Generic.ICollection<QustionDirectiveAssoc> QustionDirectiveAssocs { get; set; } // QustionDirectiveAssoc.FK_QustionDirectiveAssoc_Directive

        public Directive()
        {
            QustionDirectiveAssocs = new System.Collections.Generic.List<QustionDirectiveAssoc>();
        }
    }

}
// </auto-generated>
