// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5

using Newtonsoft.Json;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CalibrusTPV.ReversePocoGen
{

    // OrderDetail
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class OrderDetail
    {
        public int OrderDetailId { get; set; } // OrderDetailId (Primary key)
        public int TpvId { get; set; } // TPVId (Primary key)
        public string UtilityType { get; set; } // UtilityType (Primary key) (length: 50)
        public int ProgramId { get; set; } // ProgramId (Primary key)
        public string AccountType { get; set; } // AccountType (length: 50)
        public string AccountNumber { get; set; } // AccountNumber (length: 100)
        public string MeterNumber { get; set; } // MeterNumber (length: 100)
        public string RateClass { get; set; } // RateClass (length: 50)
        public string CustomerNameKey { get; set; } // CustomerNameKey (length: 50)
        public string ServiceReferenceNumber { get; set; } // ServiceReferenceNumber (length: 50)
        public string ServiceAddress { get; set; } // ServiceAddress (length: 100)
        public string ServiceCity { get; set; } // ServiceCity (length: 100)
        public string ServiceState { get; set; } // ServiceState (length: 2)
        public string ServiceZip { get; set; } // ServiceZip (length: 50)
        public string ServiceCounty { get; set; } // ServiceCounty (length: 50)
        public string BillingAddress { get; set; } // BillingAddress (length: 100)
        public string BillingCity { get; set; } // BillingCity (length: 100)
        public string BillingState { get; set; } // BillingState (length: 2)
        public string BillingZip { get; set; } // BillingZip (length: 50)
        public string BillingCounty { get; set; } // BillingCounty (length: 50)
        public string InCityLimits { get; set; } // InCityLimits (length: 50)
        public string BillingFirstName { get; set; } // BillingFirstName (length: 50)
        public string BillingLastName { get; set; } // BillingLastName (length: 50)

        // Foreign keys
        [JsonIgnore]
        public virtual Tpv Tpv { get; set; } // FK_OrderDetail_TPV
    }

}
// </auto-generated>
