// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5

using Newtonsoft.Json;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CalibrusTPV.ReversePocoGen
{

    // Question
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class Question
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name (length: 50)
        public string Description { get; set; } // Description
        public string Verbiage { get; set; } // Verbiage
        public string VerbiageSpanish { get; set; } // VerbiageSpanish
        public bool? Active { get; set; } // Active

        // Reverse navigation
        [JsonIgnore]
        public virtual System.Collections.Generic.ICollection<QustionDirectiveAssoc> QustionDirectiveAssocs { get; set; } // QustionDirectiveAssoc.FK_QustionDirectiveAssoc_Question
        [JsonIgnore]
        public virtual System.Collections.Generic.ICollection<ScriptQuestion> ScriptQuestions { get; set; } // ScriptQuestions.FK_ScriptQuestions_Question

        public Question()
        {
            QustionDirectiveAssocs = new System.Collections.Generic.List<QustionDirectiveAssoc>();
            ScriptQuestions = new System.Collections.Generic.List<ScriptQuestion>();
        }
    }

}
// </auto-generated>
