// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5

using Newtonsoft.Json;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CalibrusTPV.ReversePocoGen
{

    // States
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class State
    {
        public string StateCode { get; set; } // StateCode (Primary key) (length: 2)
        public string StateName { get; set; } // StateName (length: 50)

        // Reverse navigation
        [JsonIgnore]
        public virtual System.Collections.Generic.ICollection<ScriptQuestion> ScriptQuestions { get; set; } // ScriptQuestions.FK_ScriptQuestions_State

        public State()
        {
            ScriptQuestions = new System.Collections.Generic.List<ScriptQuestion>();
        }
    }

}
// </auto-generated>
