//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace CalibrusIVRDailyReport
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SchoolsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SchoolsEntities object using the connection string found in the 'SchoolsEntities' section of the application configuration file.
        /// </summary>
        public SchoolsEntities() : base("name=SchoolsEntities", "SchoolsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SchoolsEntities object.
        /// </summary>
        public SchoolsEntities(string connectionString) : base(connectionString, "SchoolsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SchoolsEntities object.
        /// </summary>
        public SchoolsEntities(EntityConnection connection) : base(connection, "SchoolsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblMainSchools> tblMains
        {
            get
            {
                if ((_tblMains == null))
                {
                    _tblMains = base.CreateObjectSet<tblMainSchools>("tblMains");
                }
                return _tblMains;
            }
        }
        private ObjectSet<tblMainSchools> _tblMains;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblMains EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblMains(tblMainSchools tblMain)
        {
            base.AddObject("tblMains", tblMain);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SchoolsModel", Name="tblMain")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblMainSchools : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblMain object.
        /// </summary>
        /// <param name="mainId">Initial value of the MainId property.</param>
        /// <param name="webDateTime">Initial value of the WebDateTime property.</param>
        /// <param name="claimNumber">Initial value of the ClaimNumber property.</param>
        /// <param name="adjusterId">Initial value of the AdjusterId property.</param>
        /// <param name="callLength">Initial value of the CallLength property.</param>
        /// <param name="completed">Initial value of the Completed property.</param>
        /// <param name="concern">Initial value of the Concern property.</param>
        public static tblMainSchools CreatetblMain(global::System.Int32 mainId, global::System.DateTime webDateTime, global::System.String claimNumber, global::System.String adjusterId, global::System.Int32 callLength, global::System.String completed, global::System.String concern)
        {
            tblMainSchools tblMain = new tblMainSchools();
            tblMain.MainId = mainId;
            tblMain.WebDateTime = webDateTime;
            tblMain.ClaimNumber = claimNumber;
            tblMain.AdjusterId = adjusterId;
            tblMain.CallLength = callLength;
            tblMain.Completed = completed;
            tblMain.Concern = concern;
            return tblMain;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MainId
        {
            get
            {
                return _MainId;
            }
            set
            {
                if (_MainId != value)
                {
                    OnMainIdChanging(value);
                    ReportPropertyChanging("MainId");
                    _MainId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MainId");
                    OnMainIdChanged();
                }
            }
        }
        private global::System.Int32 _MainId;
        partial void OnMainIdChanging(global::System.Int32 value);
        partial void OnMainIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime WebDateTime
        {
            get
            {
                return _WebDateTime;
            }
            set
            {
                OnWebDateTimeChanging(value);
                ReportPropertyChanging("WebDateTime");
                _WebDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WebDateTime");
                OnWebDateTimeChanged();
            }
        }
        private global::System.DateTime _WebDateTime;
        partial void OnWebDateTimeChanging(global::System.DateTime value);
        partial void OnWebDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CallDateTime
        {
            get
            {
                return _CallDateTime;
            }
            set
            {
                OnCallDateTimeChanging(value);
                ReportPropertyChanging("CallDateTime");
                _CallDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CallDateTime");
                OnCallDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CallDateTime;
        partial void OnCallDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCallDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Dnis
        {
            get
            {
                return _Dnis;
            }
            set
            {
                OnDnisChanging(value);
                ReportPropertyChanging("Dnis");
                _Dnis = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Dnis");
                OnDnisChanged();
            }
        }
        private global::System.String _Dnis;
        partial void OnDnisChanging(global::System.String value);
        partial void OnDnisChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String WavName
        {
            get
            {
                return _WavName;
            }
            set
            {
                OnWavNameChanging(value);
                ReportPropertyChanging("WavName");
                _WavName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("WavName");
                OnWavNameChanged();
            }
        }
        private global::System.String _WavName;
        partial void OnWavNameChanging(global::System.String value);
        partial void OnWavNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ClaimNumber
        {
            get
            {
                return _ClaimNumber;
            }
            set
            {
                OnClaimNumberChanging(value);
                ReportPropertyChanging("ClaimNumber");
                _ClaimNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ClaimNumber");
                OnClaimNumberChanged();
            }
        }
        private global::System.String _ClaimNumber;
        partial void OnClaimNumberChanging(global::System.String value);
        partial void OnClaimNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AdjusterId
        {
            get
            {
                return _AdjusterId;
            }
            set
            {
                OnAdjusterIdChanging(value);
                ReportPropertyChanging("AdjusterId");
                _AdjusterId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AdjusterId");
                OnAdjusterIdChanged();
            }
        }
        private global::System.String _AdjusterId;
        partial void OnAdjusterIdChanging(global::System.String value);
        partial void OnAdjusterIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RelationId
        {
            get
            {
                return _RelationId;
            }
            set
            {
                OnRelationIdChanging(value);
                ReportPropertyChanging("RelationId");
                _RelationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RelationId");
                OnRelationIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RelationId;
        partial void OnRelationIdChanging(Nullable<global::System.Int32> value);
        partial void OnRelationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CallLength
        {
            get
            {
                return _CallLength;
            }
            set
            {
                OnCallLengthChanging(value);
                ReportPropertyChanging("CallLength");
                _CallLength = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CallLength");
                OnCallLengthChanged();
            }
        }
        private global::System.Int32 _CallLength;
        partial void OnCallLengthChanging(global::System.Int32 value);
        partial void OnCallLengthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Completed
        {
            get
            {
                return _Completed;
            }
            set
            {
                OnCompletedChanging(value);
                ReportPropertyChanging("Completed");
                _Completed = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Completed");
                OnCompletedChanged();
            }
        }
        private global::System.String _Completed;
        partial void OnCompletedChanging(global::System.String value);
        partial void OnCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Concern
        {
            get
            {
                return _Concern;
            }
            set
            {
                OnConcernChanging(value);
                ReportPropertyChanging("Concern");
                _Concern = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Concern");
                OnConcernChanged();
            }
        }
        private global::System.String _Concern;
        partial void OnConcernChanging(global::System.String value);
        partial void OnConcernChanged();

        #endregion

    
    }

    #endregion

    
}
