// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CalibrusTPV.ReversePocoGen
{

    // The table 'InboundCalls' is not usable by entity framework because it
    // does not have a primary key. It is listed here for completeness.
    // InboundCalls
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class InboundCall
    {
        public string Client { get; set; } // client (length: 10)
        public string Saleschannel { get; set; } // saleschannel (length: 10)
        public string Dnis { get; set; } // dnis (length: 10)
        public string Wavname { get; set; } // wavname (length: 10)
    }

}
// </auto-generated>
