// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CalibrusTPV.ReversePocoGen
{

    public interface IScriptsContext : System.IDisposable
    {
        System.Data.Entity.DbSet<Condition> Conditions { get; set; } // Conditions
        System.Data.Entity.DbSet<Directive> Directives { get; set; } // Directives
        System.Data.Entity.DbSet<LookUp> LookUps { get; set; } // LookUps
        System.Data.Entity.DbSet<OrderDetail> OrderDetails { get; set; } // OrderDetail
        System.Data.Entity.DbSet<Question> Questions { get; set; } // Question
        System.Data.Entity.DbSet<QustionDirectiveAssoc> QustionDirectiveAssocs { get; set; } // QustionDirectiveAssoc
        System.Data.Entity.DbSet<Recording> Recordings { get; set; } // Recordings
        System.Data.Entity.DbSet<ScriptQuestion> ScriptQuestions { get; set; } // ScriptQuestions
        System.Data.Entity.DbSet<State> States { get; set; } // States
        System.Data.Entity.DbSet<Tpv> Tpvs { get; set; } // TPV
        System.Data.Entity.DbSet<VGender> VGenders { get; set; } // vGender
        System.Data.Entity.DbSet<VLookup> VLookups { get; set; } // vLookups
        System.Data.Entity.DbSet<VQtype> VQtypes { get; set; } // vQtype
        System.Data.Entity.DbSet<VSalesChannel> VSalesChannels { get; set; } // vSalesChannel

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

}
// </auto-generated>
