// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5

using Newtonsoft.Json;

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CalibrusTPV.ReversePocoGen
{

    // ScriptQuestions
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class ScriptQuestion
    {
        public int ScriptId { get; set; } // ScriptId (Primary key)
        public int QtypeId { get; set; } // QtypeId
        public string StateCode { get; set; } // StateCode (length: 2)
        public int SalesChannelId { get; set; } // SalesChannelId
        public bool Active { get; set; } // Active
        public int QuestionId { get; set; } // QuestionId
        public int ScriptOrder { get; set; } // ScriptOrder

        // Foreign keys
        [JsonIgnore]
        public virtual Question Question { get; set; } // FK_ScriptQuestions_Question
        [JsonIgnore]
        public virtual State State { get; set; } // FK_ScriptQuestions_State
    }

}
// </auto-generated>
