//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calibrus.ClearviewPortal.DataAccess.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disposition
    {
        public int DispositionsId { get; set; }
        public string Active { get; set; }
        public string Concern { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string VerCode { get; set; }
    }
}
