//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calibrus.ClearviewPortal.DataAccess.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateClassLookup
    {
        public int RateClassId { get; set; }
        public string RateClass { get; set; }
        public string LdcCode { get; set; }
        public string UtilityTypeName { get; set; }
    }
}
