//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Frontier911FailedReportExport
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FrontierEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FrontierEntities object using the connection string found in the 'FrontierEntities' section of the application configuration file.
        /// </summary>
        public FrontierEntities() : base("name=FrontierEntities", "FrontierEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FrontierEntities object.
        /// </summary>
        public FrontierEntities(string connectionString) : base(connectionString, "FrontierEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FrontierEntities object.
        /// </summary>
        public FrontierEntities(EntityConnection connection) : base(connection, "FrontierEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblE911LoadFile> tblE911LoadFile
        {
            get
            {
                if ((_tblE911LoadFile == null))
                {
                    _tblE911LoadFile = base.CreateObjectSet<tblE911LoadFile>("tblE911LoadFile");
                }
                return _tblE911LoadFile;
            }
        }
        private ObjectSet<tblE911LoadFile> _tblE911LoadFile;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblE911BrightPatternLoadFile> tblE911BrightPatternLoadFile
        {
            get
            {
                if ((_tblE911BrightPatternLoadFile == null))
                {
                    _tblE911BrightPatternLoadFile = base.CreateObjectSet<tblE911BrightPatternLoadFile>("tblE911BrightPatternLoadFile");
                }
                return _tblE911BrightPatternLoadFile;
            }
        }
        private ObjectSet<tblE911BrightPatternLoadFile> _tblE911BrightPatternLoadFile;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblE911LoadFile EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblE911LoadFile(tblE911LoadFile tblE911LoadFile)
        {
            base.AddObject("tblE911LoadFile", tblE911LoadFile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblE911BrightPatternLoadFile EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblE911BrightPatternLoadFile(tblE911BrightPatternLoadFile tblE911BrightPatternLoadFile)
        {
            base.AddObject("tblE911BrightPatternLoadFile", tblE911BrightPatternLoadFile);
        }

        #endregion

        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="startDate">No Metadata Documentation available.</param>
        /// <param name="endDate">No Metadata Documentation available.</param>
        public ObjectResult<sp911BrightPatternFailedReport_Result> sp911BrightPatternFailedReport(Nullable<global::System.DateTime> startDate, Nullable<global::System.DateTime> endDate)
        {
            ObjectParameter startDateParameter;
            if (startDate.HasValue)
            {
                startDateParameter = new ObjectParameter("StartDate", startDate);
            }
            else
            {
                startDateParameter = new ObjectParameter("StartDate", typeof(global::System.DateTime));
            }
    
            ObjectParameter endDateParameter;
            if (endDate.HasValue)
            {
                endDateParameter = new ObjectParameter("EndDate", endDate);
            }
            else
            {
                endDateParameter = new ObjectParameter("EndDate", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction<sp911BrightPatternFailedReport_Result>("sp911BrightPatternFailedReport", startDateParameter, endDateParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FrontierModel", Name="tblE911BrightPatternLoadFile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblE911BrightPatternLoadFile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblE911BrightPatternLoadFile object.
        /// </summary>
        /// <param name="e911BrightPatternLoadFileId">Initial value of the E911BrightPatternLoadFileId property.</param>
        public static tblE911BrightPatternLoadFile CreatetblE911BrightPatternLoadFile(global::System.Int32 e911BrightPatternLoadFileId)
        {
            tblE911BrightPatternLoadFile tblE911BrightPatternLoadFile = new tblE911BrightPatternLoadFile();
            tblE911BrightPatternLoadFile.E911BrightPatternLoadFileId = e911BrightPatternLoadFileId;
            return tblE911BrightPatternLoadFile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 E911BrightPatternLoadFileId
        {
            get
            {
                return _E911BrightPatternLoadFileId;
            }
            set
            {
                if (_E911BrightPatternLoadFileId != value)
                {
                    OnE911BrightPatternLoadFileIdChanging(value);
                    ReportPropertyChanging("E911BrightPatternLoadFileId");
                    _E911BrightPatternLoadFileId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("E911BrightPatternLoadFileId");
                    OnE911BrightPatternLoadFileIdChanged();
                }
            }
        }
        private global::System.Int32 _E911BrightPatternLoadFileId;
        partial void OnE911BrightPatternLoadFileIdChanging(global::System.Int32 value);
        partial void OnE911BrightPatternLoadFileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> E911LoadFileId
        {
            get
            {
                return _E911LoadFileId;
            }
            set
            {
                OnE911LoadFileIdChanging(value);
                ReportPropertyChanging("E911LoadFileId");
                _E911LoadFileId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("E911LoadFileId");
                OnE911LoadFileIdChanged();
            }
        }
        private Nullable<global::System.Int32> _E911LoadFileId;
        partial void OnE911LoadFileIdChanging(Nullable<global::System.Int32> value);
        partial void OnE911LoadFileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubscriberId
        {
            get
            {
                return _SubscriberId;
            }
            set
            {
                OnSubscriberIdChanging(value);
                ReportPropertyChanging("SubscriberId");
                _SubscriberId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubscriberId");
                OnSubscriberIdChanged();
            }
        }
        private global::System.String _SubscriberId;
        partial void OnSubscriberIdChanging(global::System.String value);
        partial void OnSubscriberIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Signature
        {
            get
            {
                return _Signature;
            }
            set
            {
                OnSignatureChanging(value);
                ReportPropertyChanging("Signature");
                _Signature = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Signature");
                OnSignatureChanged();
            }
        }
        private global::System.String _Signature;
        partial void OnSignatureChanging(global::System.String value);
        partial void OnSignatureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirthYear
        {
            get
            {
                return _BirthYear;
            }
            set
            {
                OnBirthYearChanging(value);
                ReportPropertyChanging("BirthYear");
                _BirthYear = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BirthYear");
                OnBirthYearChanged();
            }
        }
        private global::System.String _BirthYear;
        partial void OnBirthYearChanging(global::System.String value);
        partial void OnBirthYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TN
        {
            get
            {
                return _TN;
            }
            set
            {
                OnTNChanging(value);
                ReportPropertyChanging("TN");
                _TN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TN");
                OnTNChanged();
            }
        }
        private global::System.String _TN;
        partial void OnTNChanging(global::System.String value);
        partial void OnTNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GeneralAction
        {
            get
            {
                return _GeneralAction;
            }
            set
            {
                OnGeneralActionChanging(value);
                ReportPropertyChanging("GeneralAction");
                _GeneralAction = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GeneralAction");
                OnGeneralActionChanged();
            }
        }
        private global::System.String _GeneralAction;
        partial void OnGeneralActionChanging(global::System.String value);
        partial void OnGeneralActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> GeneralDate
        {
            get
            {
                return _GeneralDate;
            }
            set
            {
                OnGeneralDateChanging(value);
                ReportPropertyChanging("GeneralDate");
                _GeneralDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GeneralDate");
                OnGeneralDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _GeneralDate;
        partial void OnGeneralDateChanging(Nullable<global::System.DateTime> value);
        partial void OnGeneralDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String E911Action
        {
            get
            {
                return _E911Action;
            }
            set
            {
                OnE911ActionChanging(value);
                ReportPropertyChanging("E911Action");
                _E911Action = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("E911Action");
                OnE911ActionChanged();
            }
        }
        private global::System.String _E911Action;
        partial void OnE911ActionChanging(global::System.String value);
        partial void OnE911ActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> E911Date
        {
            get
            {
                return _E911Date;
            }
            set
            {
                OnE911DateChanging(value);
                ReportPropertyChanging("E911Date");
                _E911Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("E911Date");
                OnE911DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _E911Date;
        partial void OnE911DateChanging(Nullable<global::System.DateTime> value);
        partial void OnE911DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsData
        {
            get
            {
                return _IsData;
            }
            set
            {
                OnIsDataChanging(value);
                ReportPropertyChanging("IsData");
                _IsData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsData");
                OnIsDataChanged();
            }
        }
        private global::System.String _IsData;
        partial void OnIsDataChanging(global::System.String value);
        partial void OnIsDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsVoip
        {
            get
            {
                return _IsVoip;
            }
            set
            {
                OnIsVoipChanging(value);
                ReportPropertyChanging("IsVoip");
                _IsVoip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsVoip");
                OnIsVoipChanged();
            }
        }
        private global::System.String _IsVoip;
        partial void OnIsVoipChanging(global::System.String value);
        partial void OnIsVoipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.String _User;
        partial void OnUserChanging(global::System.String value);
        partial void OnUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DPIRegion
        {
            get
            {
                return _DPIRegion;
            }
            set
            {
                OnDPIRegionChanging(value);
                ReportPropertyChanging("DPIRegion");
                _DPIRegion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DPIRegion");
                OnDPIRegionChanged();
            }
        }
        private global::System.String _DPIRegion;
        partial void OnDPIRegionChanging(global::System.String value);
        partial void OnDPIRegionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ThisPhonenumber
        {
            get
            {
                return _ThisPhonenumber;
            }
            set
            {
                OnThisPhonenumberChanging(value);
                ReportPropertyChanging("ThisPhonenumber");
                _ThisPhonenumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ThisPhonenumber");
                OnThisPhonenumberChanged();
            }
        }
        private global::System.String _ThisPhonenumber;
        partial void OnThisPhonenumberChanging(global::System.String value);
        partial void OnThisPhonenumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsCallAttempt
        {
            get
            {
                return _IsCallAttempt;
            }
            set
            {
                OnIsCallAttemptChanging(value);
                ReportPropertyChanging("IsCallAttempt");
                _IsCallAttempt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsCallAttempt");
                OnIsCallAttemptChanged();
            }
        }
        private global::System.String _IsCallAttempt;
        partial void OnIsCallAttemptChanging(global::System.String value);
        partial void OnIsCallAttemptChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Completed
        {
            get
            {
                return _Completed;
            }
            set
            {
                OnCompletedChanging(value);
                ReportPropertyChanging("Completed");
                _Completed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Completed");
                OnCompletedChanged();
            }
        }
        private global::System.String _Completed;
        partial void OnCompletedChanging(global::System.String value);
        partial void OnCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RecordDisposition
        {
            get
            {
                return _RecordDisposition;
            }
            set
            {
                OnRecordDispositionChanging(value);
                ReportPropertyChanging("RecordDisposition");
                _RecordDisposition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RecordDisposition");
                OnRecordDispositionChanged();
            }
        }
        private global::System.String _RecordDisposition;
        partial void OnRecordDispositionChanging(global::System.String value);
        partial void OnRecordDispositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RecordDispositionCode
        {
            get
            {
                return _RecordDispositionCode;
            }
            set
            {
                OnRecordDispositionCodeChanging(value);
                ReportPropertyChanging("RecordDispositionCode");
                _RecordDispositionCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RecordDispositionCode");
                OnRecordDispositionCodeChanged();
            }
        }
        private global::System.String _RecordDispositionCode;
        partial void OnRecordDispositionCodeChanging(global::System.String value);
        partial void OnRecordDispositionCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Outofquota
        {
            get
            {
                return _Outofquota;
            }
            set
            {
                OnOutofquotaChanging(value);
                ReportPropertyChanging("Outofquota");
                _Outofquota = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Outofquota");
                OnOutofquotaChanged();
            }
        }
        private global::System.String _Outofquota;
        partial void OnOutofquotaChanging(global::System.String value);
        partial void OnOutofquotaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Quotagroup
        {
            get
            {
                return _Quotagroup;
            }
            set
            {
                OnQuotagroupChanging(value);
                ReportPropertyChanging("Quotagroup");
                _Quotagroup = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Quotagroup");
                OnQuotagroupChanged();
            }
        }
        private global::System.String _Quotagroup;
        partial void OnQuotagroupChanging(global::System.String value);
        partial void OnQuotagroupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CallDisposition
        {
            get
            {
                return _CallDisposition;
            }
            set
            {
                OnCallDispositionChanging(value);
                ReportPropertyChanging("CallDisposition");
                _CallDisposition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CallDisposition");
                OnCallDispositionChanged();
            }
        }
        private global::System.String _CallDisposition;
        partial void OnCallDispositionChanging(global::System.String value);
        partial void OnCallDispositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CallDispositionCode
        {
            get
            {
                return _CallDispositionCode;
            }
            set
            {
                OnCallDispositionCodeChanging(value);
                ReportPropertyChanging("CallDispositionCode");
                _CallDispositionCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CallDispositionCode");
                OnCallDispositionCodeChanged();
            }
        }
        private global::System.String _CallDispositionCode;
        partial void OnCallDispositionCodeChanging(global::System.String value);
        partial void OnCallDispositionCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CallNote
        {
            get
            {
                return _CallNote;
            }
            set
            {
                OnCallNoteChanging(value);
                ReportPropertyChanging("CallNote");
                _CallNote = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CallNote");
                OnCallNoteChanged();
            }
        }
        private global::System.String _CallNote;
        partial void OnCallNoteChanging(global::System.String value);
        partial void OnCallNoteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CallTime
        {
            get
            {
                return _CallTime;
            }
            set
            {
                OnCallTimeChanging(value);
                ReportPropertyChanging("CallTime");
                _CallTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CallTime");
                OnCallTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CallTime;
        partial void OnCallTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCallTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DialingDuration
        {
            get
            {
                return _DialingDuration;
            }
            set
            {
                OnDialingDurationChanging(value);
                ReportPropertyChanging("DialingDuration");
                _DialingDuration = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DialingDuration");
                OnDialingDurationChanged();
            }
        }
        private global::System.String _DialingDuration;
        partial void OnDialingDurationChanging(global::System.String value);
        partial void OnDialingDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CPADuration
        {
            get
            {
                return _CPADuration;
            }
            set
            {
                OnCPADurationChanging(value);
                ReportPropertyChanging("CPADuration");
                _CPADuration = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CPADuration");
                OnCPADurationChanged();
            }
        }
        private global::System.String _CPADuration;
        partial void OnCPADurationChanging(global::System.String value);
        partial void OnCPADurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AnsweredDuration
        {
            get
            {
                return _AnsweredDuration;
            }
            set
            {
                OnAnsweredDurationChanging(value);
                ReportPropertyChanging("AnsweredDuration");
                _AnsweredDuration = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AnsweredDuration");
                OnAnsweredDurationChanged();
            }
        }
        private global::System.String _AnsweredDuration;
        partial void OnAnsweredDurationChanging(global::System.String value);
        partial void OnAnsweredDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Agent
        {
            get
            {
                return _Agent;
            }
            set
            {
                OnAgentChanging(value);
                ReportPropertyChanging("Agent");
                _Agent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Agent");
                OnAgentChanged();
            }
        }
        private global::System.String _Agent;
        partial void OnAgentChanging(global::System.String value);
        partial void OnAgentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Connected
        {
            get
            {
                return _Connected;
            }
            set
            {
                OnConnectedChanging(value);
                ReportPropertyChanging("Connected");
                _Connected = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Connected");
                OnConnectedChanged();
            }
        }
        private global::System.String _Connected;
        partial void OnConnectedChanging(global::System.String value);
        partial void OnConnectedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CPAresult
        {
            get
            {
                return _CPAresult;
            }
            set
            {
                OnCPAresultChanging(value);
                ReportPropertyChanging("CPAresult");
                _CPAresult = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CPAresult");
                OnCPAresultChanged();
            }
        }
        private global::System.String _CPAresult;
        partial void OnCPAresultChanging(global::System.String value);
        partial void OnCPAresultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CPArecordingfile
        {
            get
            {
                return _CPArecordingfile;
            }
            set
            {
                OnCPArecordingfileChanging(value);
                ReportPropertyChanging("CPArecordingfile");
                _CPArecordingfile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CPArecordingfile");
                OnCPArecordingfileChanged();
            }
        }
        private global::System.String _CPArecordingfile;
        partial void OnCPArecordingfileChanging(global::System.String value);
        partial void OnCPArecordingfileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CPARTPserverid
        {
            get
            {
                return _CPARTPserverid;
            }
            set
            {
                OnCPARTPserveridChanging(value);
                ReportPropertyChanging("CPARTPserverid");
                _CPARTPserverid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CPARTPserverid");
                OnCPARTPserveridChanged();
            }
        }
        private global::System.String _CPARTPserverid;
        partial void OnCPARTPserveridChanging(global::System.String value);
        partial void OnCPARTPserveridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Recordingfile
        {
            get
            {
                return _Recordingfile;
            }
            set
            {
                OnRecordingfileChanging(value);
                ReportPropertyChanging("Recordingfile");
                _Recordingfile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Recordingfile");
                OnRecordingfileChanged();
            }
        }
        private global::System.String _Recordingfile;
        partial void OnRecordingfileChanging(global::System.String value);
        partial void OnRecordingfileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RTPserverid
        {
            get
            {
                return _RTPserverid;
            }
            set
            {
                OnRTPserveridChanging(value);
                ReportPropertyChanging("RTPserverid");
                _RTPserverid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RTPserverid");
                OnRTPserveridChanged();
            }
        }
        private global::System.String _RTPserverid;
        partial void OnRTPserveridChanging(global::System.String value);
        partial void OnRTPserveridChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GlobalInteractionID
        {
            get
            {
                return _GlobalInteractionID;
            }
            set
            {
                OnGlobalInteractionIDChanging(value);
                ReportPropertyChanging("GlobalInteractionID");
                _GlobalInteractionID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GlobalInteractionID");
                OnGlobalInteractionIDChanged();
            }
        }
        private global::System.String _GlobalInteractionID;
        partial void OnGlobalInteractionIDChanging(global::System.String value);
        partial void OnGlobalInteractionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RecordID
        {
            get
            {
                return _RecordID;
            }
            set
            {
                OnRecordIDChanging(value);
                ReportPropertyChanging("RecordID");
                _RecordID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RecordID");
                OnRecordIDChanged();
            }
        }
        private global::System.String _RecordID;
        partial void OnRecordIDChanging(global::System.String value);
        partial void OnRecordIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Listname
        {
            get
            {
                return _Listname;
            }
            set
            {
                OnListnameChanging(value);
                ReportPropertyChanging("Listname");
                _Listname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Listname");
                OnListnameChanged();
            }
        }
        private global::System.String _Listname;
        partial void OnListnameChanging(global::System.String value);
        partial void OnListnameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FrontierModel", Name="tblE911LoadFile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblE911LoadFile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblE911LoadFile object.
        /// </summary>
        /// <param name="e911LoadFileId">Initial value of the E911LoadFileId property.</param>
        public static tblE911LoadFile CreatetblE911LoadFile(global::System.Int32 e911LoadFileId)
        {
            tblE911LoadFile tblE911LoadFile = new tblE911LoadFile();
            tblE911LoadFile.E911LoadFileId = e911LoadFileId;
            return tblE911LoadFile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 E911LoadFileId
        {
            get
            {
                return _E911LoadFileId;
            }
            set
            {
                if (_E911LoadFileId != value)
                {
                    OnE911LoadFileIdChanging(value);
                    ReportPropertyChanging("E911LoadFileId");
                    _E911LoadFileId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("E911LoadFileId");
                    OnE911LoadFileIdChanged();
                }
            }
        }
        private global::System.Int32 _E911LoadFileId;
        partial void OnE911LoadFileIdChanging(global::System.Int32 value);
        partial void OnE911LoadFileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LoadDateTime
        {
            get
            {
                return _LoadDateTime;
            }
            set
            {
                OnLoadDateTimeChanging(value);
                ReportPropertyChanging("LoadDateTime");
                _LoadDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoadDateTime");
                OnLoadDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LoadDateTime;
        partial void OnLoadDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLoadDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private Nullable<global::System.Int32> _Priority;
        partial void OnPriorityChanging(Nullable<global::System.Int32> value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TimeZone
        {
            get
            {
                return _TimeZone;
            }
            set
            {
                OnTimeZoneChanging(value);
                ReportPropertyChanging("TimeZone");
                _TimeZone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeZone");
                OnTimeZoneChanged();
            }
        }
        private Nullable<global::System.Int32> _TimeZone;
        partial void OnTimeZoneChanging(Nullable<global::System.Int32> value);
        partial void OnTimeZoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Attempts
        {
            get
            {
                return _Attempts;
            }
            set
            {
                OnAttemptsChanging(value);
                ReportPropertyChanging("Attempts");
                _Attempts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Attempts");
                OnAttemptsChanged();
            }
        }
        private Nullable<global::System.Int32> _Attempts;
        partial void OnAttemptsChanging(Nullable<global::System.Int32> value);
        partial void OnAttemptsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Processed
        {
            get
            {
                return _Processed;
            }
            set
            {
                OnProcessedChanging(value);
                ReportPropertyChanging("Processed");
                _Processed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Processed");
                OnProcessedChanged();
            }
        }
        private global::System.String _Processed;
        partial void OnProcessedChanging(global::System.String value);
        partial void OnProcessedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Locked
        {
            get
            {
                return _Locked;
            }
            set
            {
                OnLockedChanging(value);
                ReportPropertyChanging("Locked");
                _Locked = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Locked");
                OnLockedChanged();
            }
        }
        private global::System.String _Locked;
        partial void OnLockedChanging(global::System.String value);
        partial void OnLockedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LockedDateTime
        {
            get
            {
                return _LockedDateTime;
            }
            set
            {
                OnLockedDateTimeChanging(value);
                ReportPropertyChanging("LockedDateTime");
                _LockedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LockedDateTime");
                OnLockedDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LockedDateTime;
        partial void OnLockedDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLockedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LockedAgentId
        {
            get
            {
                return _LockedAgentId;
            }
            set
            {
                OnLockedAgentIdChanging(value);
                ReportPropertyChanging("LockedAgentId");
                _LockedAgentId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LockedAgentId");
                OnLockedAgentIdChanged();
            }
        }
        private global::System.String _LockedAgentId;
        partial void OnLockedAgentIdChanging(global::System.String value);
        partial void OnLockedAgentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastAttemptDate
        {
            get
            {
                return _LastAttemptDate;
            }
            set
            {
                OnLastAttemptDateChanging(value);
                ReportPropertyChanging("LastAttemptDate");
                _LastAttemptDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastAttemptDate");
                OnLastAttemptDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastAttemptDate;
        partial void OnLastAttemptDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastAttemptDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastDisposition
        {
            get
            {
                return _LastDisposition;
            }
            set
            {
                OnLastDispositionChanging(value);
                ReportPropertyChanging("LastDisposition");
                _LastDisposition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastDisposition");
                OnLastDispositionChanged();
            }
        }
        private global::System.String _LastDisposition;
        partial void OnLastDispositionChanging(global::System.String value);
        partial void OnLastDispositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastDispositionCode
        {
            get
            {
                return _LastDispositionCode;
            }
            set
            {
                OnLastDispositionCodeChanging(value);
                ReportPropertyChanging("LastDispositionCode");
                _LastDispositionCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastDispositionCode");
                OnLastDispositionCodeChanged();
            }
        }
        private global::System.String _LastDispositionCode;
        partial void OnLastDispositionCodeChanging(global::System.String value);
        partial void OnLastDispositionCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubscriberId
        {
            get
            {
                return _SubscriberId;
            }
            set
            {
                OnSubscriberIdChanging(value);
                ReportPropertyChanging("SubscriberId");
                _SubscriberId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubscriberId");
                OnSubscriberIdChanged();
            }
        }
        private global::System.String _SubscriberId;
        partial void OnSubscriberIdChanging(global::System.String value);
        partial void OnSubscriberIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Signature
        {
            get
            {
                return _Signature;
            }
            set
            {
                OnSignatureChanging(value);
                ReportPropertyChanging("Signature");
                _Signature = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Signature");
                OnSignatureChanged();
            }
        }
        private global::System.String _Signature;
        partial void OnSignatureChanging(global::System.String value);
        partial void OnSignatureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirthYear
        {
            get
            {
                return _BirthYear;
            }
            set
            {
                OnBirthYearChanging(value);
                ReportPropertyChanging("BirthYear");
                _BirthYear = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BirthYear");
                OnBirthYearChanged();
            }
        }
        private global::System.String _BirthYear;
        partial void OnBirthYearChanging(global::System.String value);
        partial void OnBirthYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TN
        {
            get
            {
                return _TN;
            }
            set
            {
                OnTNChanging(value);
                ReportPropertyChanging("TN");
                _TN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TN");
                OnTNChanged();
            }
        }
        private global::System.String _TN;
        partial void OnTNChanging(global::System.String value);
        partial void OnTNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GeneralAction
        {
            get
            {
                return _GeneralAction;
            }
            set
            {
                OnGeneralActionChanging(value);
                ReportPropertyChanging("GeneralAction");
                _GeneralAction = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GeneralAction");
                OnGeneralActionChanged();
            }
        }
        private global::System.String _GeneralAction;
        partial void OnGeneralActionChanging(global::System.String value);
        partial void OnGeneralActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> GeneralDate
        {
            get
            {
                return _GeneralDate;
            }
            set
            {
                OnGeneralDateChanging(value);
                ReportPropertyChanging("GeneralDate");
                _GeneralDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GeneralDate");
                OnGeneralDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _GeneralDate;
        partial void OnGeneralDateChanging(Nullable<global::System.DateTime> value);
        partial void OnGeneralDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String E911Action
        {
            get
            {
                return _E911Action;
            }
            set
            {
                OnE911ActionChanging(value);
                ReportPropertyChanging("E911Action");
                _E911Action = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("E911Action");
                OnE911ActionChanged();
            }
        }
        private global::System.String _E911Action;
        partial void OnE911ActionChanging(global::System.String value);
        partial void OnE911ActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> E911Date
        {
            get
            {
                return _E911Date;
            }
            set
            {
                OnE911DateChanging(value);
                ReportPropertyChanging("E911Date");
                _E911Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("E911Date");
                OnE911DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _E911Date;
        partial void OnE911DateChanging(Nullable<global::System.DateTime> value);
        partial void OnE911DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsData
        {
            get
            {
                return _IsData;
            }
            set
            {
                OnIsDataChanging(value);
                ReportPropertyChanging("IsData");
                _IsData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsData");
                OnIsDataChanged();
            }
        }
        private global::System.String _IsData;
        partial void OnIsDataChanging(global::System.String value);
        partial void OnIsDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsVoip
        {
            get
            {
                return _IsVoip;
            }
            set
            {
                OnIsVoipChanging(value);
                ReportPropertyChanging("IsVoip");
                _IsVoip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsVoip");
                OnIsVoipChanged();
            }
        }
        private global::System.String _IsVoip;
        partial void OnIsVoipChanging(global::System.String value);
        partial void OnIsVoipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.String _User;
        partial void OnUserChanging(global::System.String value);
        partial void OnUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DPIRegion
        {
            get
            {
                return _DPIRegion;
            }
            set
            {
                OnDPIRegionChanging(value);
                ReportPropertyChanging("DPIRegion");
                _DPIRegion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DPIRegion");
                OnDPIRegionChanged();
            }
        }
        private global::System.String _DPIRegion;
        partial void OnDPIRegionChanging(global::System.String value);
        partial void OnDPIRegionChanged();

        #endregion

    
    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="FrontierModel", Name="sp911BrightPatternFailedReport_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class sp911BrightPatternFailedReport_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sp911BrightPatternFailedReport_Result object.
        /// </summary>
        /// <param name="customer_Accepted">Initial value of the Customer_Accepted property.</param>
        /// <param name="customer_To_Be_Disconnected">Initial value of the Customer_To_Be_Disconnected property.</param>
        public static sp911BrightPatternFailedReport_Result Createsp911BrightPatternFailedReport_Result(global::System.String customer_Accepted, global::System.String customer_To_Be_Disconnected)
        {
            sp911BrightPatternFailedReport_Result sp911BrightPatternFailedReport_Result = new sp911BrightPatternFailedReport_Result();
            sp911BrightPatternFailedReport_Result.Customer_Accepted = customer_Accepted;
            sp911BrightPatternFailedReport_Result.Customer_To_Be_Disconnected = customer_To_Be_Disconnected;
            return sp911BrightPatternFailedReport_Result;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubscriberId
        {
            get
            {
                return _SubscriberId;
            }
            set
            {
                OnSubscriberIdChanging(value);
                ReportPropertyChanging("SubscriberId");
                _SubscriberId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubscriberId");
                OnSubscriberIdChanged();
            }
        }
        private global::System.String _SubscriberId;
        partial void OnSubscriberIdChanging(global::System.String value);
        partial void OnSubscriberIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Signature
        {
            get
            {
                return _Signature;
            }
            set
            {
                OnSignatureChanging(value);
                ReportPropertyChanging("Signature");
                _Signature = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Signature");
                OnSignatureChanged();
            }
        }
        private global::System.String _Signature;
        partial void OnSignatureChanging(global::System.String value);
        partial void OnSignatureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirthYear
        {
            get
            {
                return _BirthYear;
            }
            set
            {
                OnBirthYearChanging(value);
                ReportPropertyChanging("BirthYear");
                _BirthYear = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BirthYear");
                OnBirthYearChanged();
            }
        }
        private global::System.String _BirthYear;
        partial void OnBirthYearChanging(global::System.String value);
        partial void OnBirthYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TN
        {
            get
            {
                return _TN;
            }
            set
            {
                OnTNChanging(value);
                ReportPropertyChanging("TN");
                _TN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TN");
                OnTNChanged();
            }
        }
        private global::System.String _TN;
        partial void OnTNChanging(global::System.String value);
        partial void OnTNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GeneralAction
        {
            get
            {
                return _GeneralAction;
            }
            set
            {
                OnGeneralActionChanging(value);
                ReportPropertyChanging("GeneralAction");
                _GeneralAction = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GeneralAction");
                OnGeneralActionChanged();
            }
        }
        private global::System.String _GeneralAction;
        partial void OnGeneralActionChanging(global::System.String value);
        partial void OnGeneralActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> GeneralDate
        {
            get
            {
                return _GeneralDate;
            }
            set
            {
                OnGeneralDateChanging(value);
                ReportPropertyChanging("GeneralDate");
                _GeneralDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GeneralDate");
                OnGeneralDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _GeneralDate;
        partial void OnGeneralDateChanging(Nullable<global::System.DateTime> value);
        partial void OnGeneralDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String E911Action
        {
            get
            {
                return _E911Action;
            }
            set
            {
                OnE911ActionChanging(value);
                ReportPropertyChanging("E911Action");
                _E911Action = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("E911Action");
                OnE911ActionChanged();
            }
        }
        private global::System.String _E911Action;
        partial void OnE911ActionChanging(global::System.String value);
        partial void OnE911ActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> E911Date
        {
            get
            {
                return _E911Date;
            }
            set
            {
                OnE911DateChanging(value);
                ReportPropertyChanging("E911Date");
                _E911Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("E911Date");
                OnE911DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _E911Date;
        partial void OnE911DateChanging(Nullable<global::System.DateTime> value);
        partial void OnE911DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsData
        {
            get
            {
                return _IsData;
            }
            set
            {
                OnIsDataChanging(value);
                ReportPropertyChanging("IsData");
                _IsData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsData");
                OnIsDataChanged();
            }
        }
        private global::System.String _IsData;
        partial void OnIsDataChanging(global::System.String value);
        partial void OnIsDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsVoip
        {
            get
            {
                return _IsVoip;
            }
            set
            {
                OnIsVoipChanging(value);
                ReportPropertyChanging("IsVoip");
                _IsVoip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsVoip");
                OnIsVoipChanged();
            }
        }
        private global::System.String _IsVoip;
        partial void OnIsVoipChanging(global::System.String value);
        partial void OnIsVoipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.String _User;
        partial void OnUserChanging(global::System.String value);
        partial void OnUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CallTime
        {
            get
            {
                return _CallTime;
            }
            set
            {
                OnCallTimeChanging(value);
                ReportPropertyChanging("CallTime");
                _CallTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CallTime");
                OnCallTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CallTime;
        partial void OnCallTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCallTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Customer_Accepted
        {
            get
            {
                return _Customer_Accepted;
            }
            set
            {
                OnCustomer_AcceptedChanging(value);
                ReportPropertyChanging("Customer_Accepted");
                _Customer_Accepted = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Customer_Accepted");
                OnCustomer_AcceptedChanged();
            }
        }
        private global::System.String _Customer_Accepted;
        partial void OnCustomer_AcceptedChanging(global::System.String value);
        partial void OnCustomer_AcceptedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Customer_To_Be_Disconnected
        {
            get
            {
                return _Customer_To_Be_Disconnected;
            }
            set
            {
                OnCustomer_To_Be_DisconnectedChanging(value);
                ReportPropertyChanging("Customer_To_Be_Disconnected");
                _Customer_To_Be_Disconnected = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Customer_To_Be_Disconnected");
                OnCustomer_To_Be_DisconnectedChanged();
            }
        }
        private global::System.String _Customer_To_Be_Disconnected;
        partial void OnCustomer_To_Be_DisconnectedChanging(global::System.String value);
        partial void OnCustomer_To_Be_DisconnectedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CallDispositionCode
        {
            get
            {
                return _CallDispositionCode;
            }
            set
            {
                OnCallDispositionCodeChanging(value);
                ReportPropertyChanging("CallDispositionCode");
                _CallDispositionCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CallDispositionCode");
                OnCallDispositionCodeChanged();
            }
        }
        private global::System.String _CallDispositionCode;
        partial void OnCallDispositionCodeChanging(global::System.String value);
        partial void OnCallDispositionCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Attempts
        {
            get
            {
                return _Attempts;
            }
            set
            {
                OnAttemptsChanging(value);
                ReportPropertyChanging("Attempts");
                _Attempts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Attempts");
                OnAttemptsChanged();
            }
        }
        private Nullable<global::System.Int32> _Attempts;
        partial void OnAttemptsChanging(Nullable<global::System.Int32> value);
        partial void OnAttemptsChanged();

        #endregion

    }

    #endregion

    
}
