//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calibrus.SparkPortal.DataAccess.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremiseType
    {
        public PremiseType()
        {
            this.Programs = new HashSet<Program>();
        }
    
        public int PremiseTypeId { get; set; }
        public string PremiseTypeName { get; set; }
        public bool IsActive { get; set; }
        public int DisplayOrder { get; set; }
    
        public virtual ICollection<Program> Programs { get; set; }
    }
}
