//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calibrus.SparkPortal.DataAccess.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public Program()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ProgramVendors = new HashSet<ProgramVendor>();
            this.SalesChannelPrograms = new HashSet<SalesChannelProgram>();
        }
    
        public int ProgramId { get; set; }
        public string ProgramCode { get; set; }
        public string ProgramName { get; set; }
        public string ProgramDescription { get; set; }
        public string DefaultPricingPlanDescription { get; set; }
        public System.DateTime EffectiveStartDate { get; set; }
        public System.DateTime EffectiveEndDate { get; set; }
        public Nullable<decimal> Msf { get; set; }
        public Nullable<decimal> Etf { get; set; }
        public decimal Rate { get; set; }
        public string PromotionalCode { get; set; }
        public int UnitOfMeasureId { get; set; }
        public Nullable<int> Term { get; set; }
        public Nullable<int> UtilityTypeId { get; set; }
        public Nullable<int> PremiseTypeId { get; set; }
        public string State { get; set; }
        public int UtilityId { get; set; }
        public int AccountNumberTypeId { get; set; }
        public int AccountNumberLength { get; set; }
        public Nullable<bool> AccountNumberFixedLength { get; set; }
        public Nullable<bool> MeterNumber { get; set; }
        public Nullable<int> MeterNumberLength { get; set; }
        public Nullable<int> RescindBy { get; set; }
        public Nullable<bool> Hefpa { get; set; }
        public string RateVerbiage { get; set; }
        public string CancellationVerbiage { get; set; }
        public string RateVerbiageSpanish { get; set; }
        public string CancellationVerbiageSpanish { get; set; }
        public string Vendor { get; set; }
        public string SalesChannel { get; set; }
        public string Market { get; set; }
        public int BrandId { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public bool ServiceReference { get; set; }
        public bool CreditCheck { get; set; }
        public string ServiceReferenceNumver { get; set; }
    
        public virtual AccountNumberType AccountNumberType { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual PremiseType PremiseType { get; set; }
        public virtual UnitOfMeasure UnitOfMeasure { get; set; }
        public virtual Utility Utility { get; set; }
        public virtual UtilityType UtilityType { get; set; }
        public virtual ICollection<ProgramVendor> ProgramVendors { get; set; }
        public virtual ICollection<SalesChannelProgram> SalesChannelPrograms { get; set; }
    }
}
