//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constellation_EnrollInHomeServices
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConstellationEntities : DbContext
    {
        public ConstellationEntities()
            : base("name=ConstellationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblHomeService> tblHomeServices { get; set; }
        public DbSet<tblHomeServicesPlan> tblHomeServicesPlans { get; set; }
        public DbSet<tblHomeServicesResponse> tblHomeServicesResponses { get; set; }
        public DbSet<tblMain> tblMains { get; set; }
        public DbSet<tblVendor> tblVendors { get; set; }
        public DbSet<tblHomeServicesZipCodeLookUp> tblHomeServicesZipCodeLookUps { get; set; }
    }
}
