//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Constellation_EnrollInHomeServices
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHomeServicesResponse
    {
        public int HomeServicesResponseId { get; set; }
        public int HomeServicesId { get; set; }
        public System.DateTime CompletedDateTime { get; set; }
        public string ResponseSent { get; set; }
        public Nullable<System.DateTime> ResponseDateTime { get; set; }
        public string Status { get; set; }
        public string OperationResult { get; set; }
        public string ObjectSent { get; set; }
    }
}
