//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearviewScriptViewer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptLookup
    {
        public int ScriptLookupId { get; set; }
        public string Dnis { get; set; }
        public string State { get; set; }
        public string SalesChannel { get; set; }
        public string Script { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
