//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace FrontierE911LaodFileInsert
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class FrontierEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new FrontierEntities object using the connection string found in the 'FrontierEntities' section of the application configuration file.
        /// </summary>
        public FrontierEntities() : base("name=FrontierEntities", "FrontierEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FrontierEntities object.
        /// </summary>
        public FrontierEntities(string connectionString) : base(connectionString, "FrontierEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new FrontierEntities object.
        /// </summary>
        public FrontierEntities(EntityConnection connection) : base(connection, "FrontierEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblE911LoadFile> tblE911LoadFile
        {
            get
            {
                if ((_tblE911LoadFile == null))
                {
                    _tblE911LoadFile = base.CreateObjectSet<tblE911LoadFile>("tblE911LoadFile");
                }
                return _tblE911LoadFile;
            }
        }
        private ObjectSet<tblE911LoadFile> _tblE911LoadFile;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblE911LoadFileTempHold> tblE911LoadFileTempHold
        {
            get
            {
                if ((_tblE911LoadFileTempHold == null))
                {
                    _tblE911LoadFileTempHold = base.CreateObjectSet<tblE911LoadFileTempHold>("tblE911LoadFileTempHold");
                }
                return _tblE911LoadFileTempHold;
            }
        }
        private ObjectSet<tblE911LoadFileTempHold> _tblE911LoadFileTempHold;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblE911LoadFile EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblE911LoadFile(tblE911LoadFile tblE911LoadFile)
        {
            base.AddObject("tblE911LoadFile", tblE911LoadFile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblE911LoadFileTempHold EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblE911LoadFileTempHold(tblE911LoadFileTempHold tblE911LoadFileTempHold)
        {
            base.AddObject("tblE911LoadFileTempHold", tblE911LoadFileTempHold);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FrontierModel", Name="tblE911LoadFile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblE911LoadFile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblE911LoadFile object.
        /// </summary>
        /// <param name="e911LoadFileId">Initial value of the E911LoadFileId property.</param>
        public static tblE911LoadFile CreatetblE911LoadFile(global::System.Int32 e911LoadFileId)
        {
            tblE911LoadFile tblE911LoadFile = new tblE911LoadFile();
            tblE911LoadFile.E911LoadFileId = e911LoadFileId;
            return tblE911LoadFile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 E911LoadFileId
        {
            get
            {
                return _E911LoadFileId;
            }
            set
            {
                if (_E911LoadFileId != value)
                {
                    OnE911LoadFileIdChanging(value);
                    ReportPropertyChanging("E911LoadFileId");
                    _E911LoadFileId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("E911LoadFileId");
                    OnE911LoadFileIdChanged();
                }
            }
        }
        private global::System.Int32 _E911LoadFileId;
        partial void OnE911LoadFileIdChanging(global::System.Int32 value);
        partial void OnE911LoadFileIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LoadDateTime
        {
            get
            {
                return _LoadDateTime;
            }
            set
            {
                OnLoadDateTimeChanging(value);
                ReportPropertyChanging("LoadDateTime");
                _LoadDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoadDateTime");
                OnLoadDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LoadDateTime;
        partial void OnLoadDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLoadDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private Nullable<global::System.Int32> _Priority;
        partial void OnPriorityChanging(Nullable<global::System.Int32> value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TimeZone
        {
            get
            {
                return _TimeZone;
            }
            set
            {
                OnTimeZoneChanging(value);
                ReportPropertyChanging("TimeZone");
                _TimeZone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeZone");
                OnTimeZoneChanged();
            }
        }
        private Nullable<global::System.Int32> _TimeZone;
        partial void OnTimeZoneChanging(Nullable<global::System.Int32> value);
        partial void OnTimeZoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Attempts
        {
            get
            {
                return _Attempts;
            }
            set
            {
                OnAttemptsChanging(value);
                ReportPropertyChanging("Attempts");
                _Attempts = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Attempts");
                OnAttemptsChanged();
            }
        }
        private Nullable<global::System.Int32> _Attempts;
        partial void OnAttemptsChanging(Nullable<global::System.Int32> value);
        partial void OnAttemptsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Processed
        {
            get
            {
                return _Processed;
            }
            set
            {
                OnProcessedChanging(value);
                ReportPropertyChanging("Processed");
                _Processed = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Processed");
                OnProcessedChanged();
            }
        }
        private global::System.String _Processed;
        partial void OnProcessedChanging(global::System.String value);
        partial void OnProcessedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Locked
        {
            get
            {
                return _Locked;
            }
            set
            {
                OnLockedChanging(value);
                ReportPropertyChanging("Locked");
                _Locked = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Locked");
                OnLockedChanged();
            }
        }
        private global::System.String _Locked;
        partial void OnLockedChanging(global::System.String value);
        partial void OnLockedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LockedDateTime
        {
            get
            {
                return _LockedDateTime;
            }
            set
            {
                OnLockedDateTimeChanging(value);
                ReportPropertyChanging("LockedDateTime");
                _LockedDateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LockedDateTime");
                OnLockedDateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LockedDateTime;
        partial void OnLockedDateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLockedDateTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LockedAgentId
        {
            get
            {
                return _LockedAgentId;
            }
            set
            {
                OnLockedAgentIdChanging(value);
                ReportPropertyChanging("LockedAgentId");
                _LockedAgentId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LockedAgentId");
                OnLockedAgentIdChanged();
            }
        }
        private global::System.String _LockedAgentId;
        partial void OnLockedAgentIdChanging(global::System.String value);
        partial void OnLockedAgentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastAttemptDate
        {
            get
            {
                return _LastAttemptDate;
            }
            set
            {
                OnLastAttemptDateChanging(value);
                ReportPropertyChanging("LastAttemptDate");
                _LastAttemptDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastAttemptDate");
                OnLastAttemptDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastAttemptDate;
        partial void OnLastAttemptDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastAttemptDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastDisposition
        {
            get
            {
                return _LastDisposition;
            }
            set
            {
                OnLastDispositionChanging(value);
                ReportPropertyChanging("LastDisposition");
                _LastDisposition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastDisposition");
                OnLastDispositionChanged();
            }
        }
        private global::System.String _LastDisposition;
        partial void OnLastDispositionChanging(global::System.String value);
        partial void OnLastDispositionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastDispositionCode
        {
            get
            {
                return _LastDispositionCode;
            }
            set
            {
                OnLastDispositionCodeChanging(value);
                ReportPropertyChanging("LastDispositionCode");
                _LastDispositionCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastDispositionCode");
                OnLastDispositionCodeChanged();
            }
        }
        private global::System.String _LastDispositionCode;
        partial void OnLastDispositionCodeChanging(global::System.String value);
        partial void OnLastDispositionCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SubscriberId
        {
            get
            {
                return _SubscriberId;
            }
            set
            {
                OnSubscriberIdChanging(value);
                ReportPropertyChanging("SubscriberId");
                _SubscriberId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SubscriberId");
                OnSubscriberIdChanged();
            }
        }
        private global::System.String _SubscriberId;
        partial void OnSubscriberIdChanging(global::System.String value);
        partial void OnSubscriberIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Signature
        {
            get
            {
                return _Signature;
            }
            set
            {
                OnSignatureChanging(value);
                ReportPropertyChanging("Signature");
                _Signature = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Signature");
                OnSignatureChanged();
            }
        }
        private global::System.String _Signature;
        partial void OnSignatureChanging(global::System.String value);
        partial void OnSignatureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirthYear
        {
            get
            {
                return _BirthYear;
            }
            set
            {
                OnBirthYearChanging(value);
                ReportPropertyChanging("BirthYear");
                _BirthYear = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BirthYear");
                OnBirthYearChanged();
            }
        }
        private global::System.String _BirthYear;
        partial void OnBirthYearChanging(global::System.String value);
        partial void OnBirthYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TN
        {
            get
            {
                return _TN;
            }
            set
            {
                OnTNChanging(value);
                ReportPropertyChanging("TN");
                _TN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TN");
                OnTNChanged();
            }
        }
        private global::System.String _TN;
        partial void OnTNChanging(global::System.String value);
        partial void OnTNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GeneralAction
        {
            get
            {
                return _GeneralAction;
            }
            set
            {
                OnGeneralActionChanging(value);
                ReportPropertyChanging("GeneralAction");
                _GeneralAction = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GeneralAction");
                OnGeneralActionChanged();
            }
        }
        private global::System.String _GeneralAction;
        partial void OnGeneralActionChanging(global::System.String value);
        partial void OnGeneralActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> GeneralDate
        {
            get
            {
                return _GeneralDate;
            }
            set
            {
                OnGeneralDateChanging(value);
                ReportPropertyChanging("GeneralDate");
                _GeneralDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GeneralDate");
                OnGeneralDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _GeneralDate;
        partial void OnGeneralDateChanging(Nullable<global::System.DateTime> value);
        partial void OnGeneralDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String E911Action
        {
            get
            {
                return _E911Action;
            }
            set
            {
                OnE911ActionChanging(value);
                ReportPropertyChanging("E911Action");
                _E911Action = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("E911Action");
                OnE911ActionChanged();
            }
        }
        private global::System.String _E911Action;
        partial void OnE911ActionChanging(global::System.String value);
        partial void OnE911ActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> E911Date
        {
            get
            {
                return _E911Date;
            }
            set
            {
                OnE911DateChanging(value);
                ReportPropertyChanging("E911Date");
                _E911Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("E911Date");
                OnE911DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _E911Date;
        partial void OnE911DateChanging(Nullable<global::System.DateTime> value);
        partial void OnE911DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsData
        {
            get
            {
                return _IsData;
            }
            set
            {
                OnIsDataChanging(value);
                ReportPropertyChanging("IsData");
                _IsData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsData");
                OnIsDataChanged();
            }
        }
        private global::System.String _IsData;
        partial void OnIsDataChanging(global::System.String value);
        partial void OnIsDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsVoip
        {
            get
            {
                return _IsVoip;
            }
            set
            {
                OnIsVoipChanging(value);
                ReportPropertyChanging("IsVoip");
                _IsVoip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsVoip");
                OnIsVoipChanged();
            }
        }
        private global::System.String _IsVoip;
        partial void OnIsVoipChanging(global::System.String value);
        partial void OnIsVoipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.String _User;
        partial void OnUserChanging(global::System.String value);
        partial void OnUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DPIRegion
        {
            get
            {
                return _DPIRegion;
            }
            set
            {
                OnDPIRegionChanging(value);
                ReportPropertyChanging("DPIRegion");
                _DPIRegion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DPIRegion");
                OnDPIRegionChanged();
            }
        }
        private global::System.String _DPIRegion;
        partial void OnDPIRegionChanging(global::System.String value);
        partial void OnDPIRegionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="FrontierModel", Name="tblE911LoadFileTempHold")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblE911LoadFileTempHold : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblE911LoadFileTempHold object.
        /// </summary>
        /// <param name="subscriberId">Initial value of the SubscriberId property.</param>
        public static tblE911LoadFileTempHold CreatetblE911LoadFileTempHold(global::System.String subscriberId)
        {
            tblE911LoadFileTempHold tblE911LoadFileTempHold = new tblE911LoadFileTempHold();
            tblE911LoadFileTempHold.SubscriberId = subscriberId;
            return tblE911LoadFileTempHold;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SubscriberId
        {
            get
            {
                return _SubscriberId;
            }
            set
            {
                if (_SubscriberId != value)
                {
                    OnSubscriberIdChanging(value);
                    ReportPropertyChanging("SubscriberId");
                    _SubscriberId = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SubscriberId");
                    OnSubscriberIdChanged();
                }
            }
        }
        private global::System.String _SubscriberId;
        partial void OnSubscriberIdChanging(global::System.String value);
        partial void OnSubscriberIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Signature
        {
            get
            {
                return _Signature;
            }
            set
            {
                OnSignatureChanging(value);
                ReportPropertyChanging("Signature");
                _Signature = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Signature");
                OnSignatureChanged();
            }
        }
        private global::System.String _Signature;
        partial void OnSignatureChanging(global::System.String value);
        partial void OnSignatureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirthYear
        {
            get
            {
                return _BirthYear;
            }
            set
            {
                OnBirthYearChanging(value);
                ReportPropertyChanging("BirthYear");
                _BirthYear = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BirthYear");
                OnBirthYearChanged();
            }
        }
        private global::System.String _BirthYear;
        partial void OnBirthYearChanging(global::System.String value);
        partial void OnBirthYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TN
        {
            get
            {
                return _TN;
            }
            set
            {
                OnTNChanging(value);
                ReportPropertyChanging("TN");
                _TN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TN");
                OnTNChanged();
            }
        }
        private global::System.String _TN;
        partial void OnTNChanging(global::System.String value);
        partial void OnTNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GeneralAction
        {
            get
            {
                return _GeneralAction;
            }
            set
            {
                OnGeneralActionChanging(value);
                ReportPropertyChanging("GeneralAction");
                _GeneralAction = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GeneralAction");
                OnGeneralActionChanged();
            }
        }
        private global::System.String _GeneralAction;
        partial void OnGeneralActionChanging(global::System.String value);
        partial void OnGeneralActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> GeneralDate
        {
            get
            {
                return _GeneralDate;
            }
            set
            {
                OnGeneralDateChanging(value);
                ReportPropertyChanging("GeneralDate");
                _GeneralDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GeneralDate");
                OnGeneralDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _GeneralDate;
        partial void OnGeneralDateChanging(Nullable<global::System.DateTime> value);
        partial void OnGeneralDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String E911Action
        {
            get
            {
                return _E911Action;
            }
            set
            {
                OnE911ActionChanging(value);
                ReportPropertyChanging("E911Action");
                _E911Action = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("E911Action");
                OnE911ActionChanged();
            }
        }
        private global::System.String _E911Action;
        partial void OnE911ActionChanging(global::System.String value);
        partial void OnE911ActionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> E911Date
        {
            get
            {
                return _E911Date;
            }
            set
            {
                OnE911DateChanging(value);
                ReportPropertyChanging("E911Date");
                _E911Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("E911Date");
                OnE911DateChanged();
            }
        }
        private Nullable<global::System.DateTime> _E911Date;
        partial void OnE911DateChanging(Nullable<global::System.DateTime> value);
        partial void OnE911DateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsData
        {
            get
            {
                return _IsData;
            }
            set
            {
                OnIsDataChanging(value);
                ReportPropertyChanging("IsData");
                _IsData = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsData");
                OnIsDataChanged();
            }
        }
        private global::System.String _IsData;
        partial void OnIsDataChanging(global::System.String value);
        partial void OnIsDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IsVoip
        {
            get
            {
                return _IsVoip;
            }
            set
            {
                OnIsVoipChanging(value);
                ReportPropertyChanging("IsVoip");
                _IsVoip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IsVoip");
                OnIsVoipChanged();
            }
        }
        private global::System.String _IsVoip;
        partial void OnIsVoipChanging(global::System.String value);
        partial void OnIsVoipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String User
        {
            get
            {
                return _User;
            }
            set
            {
                OnUserChanging(value);
                ReportPropertyChanging("User");
                _User = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("User");
                OnUserChanged();
            }
        }
        private global::System.String _User;
        partial void OnUserChanging(global::System.String value);
        partial void OnUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DPIRegion
        {
            get
            {
                return _DPIRegion;
            }
            set
            {
                OnDPIRegionChanging(value);
                ReportPropertyChanging("DPIRegion");
                _DPIRegion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DPIRegion");
                OnDPIRegionChanged();
            }
        }
        private global::System.String _DPIRegion;
        partial void OnDPIRegionChanging(global::System.String value);
        partial void OnDPIRegionChanged();

        #endregion

    
    }

    #endregion

    
}
