//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calibrus.SparkPortal.DataAccess.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentCustomer
    {
        public int Id { get; set; }
        public string Utility { get; set; }
        public string Commodity { get; set; }
        public string AccountNumber { get; set; }
        public string Phone { get; set; }
    }
}
