//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calibrus.SparkPortal.DataAccess.Infrastructure
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public Office()
        {
            this.Users = new HashSet<User>();
        }
    
        public int OfficeId { get; set; }
        public int VendorId { get; set; }
        public string OfficeName { get; set; }
        public string OfficeEmail { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string ModifiedBy { get; set; }
        public string MarketerCode { get; set; }
        public int SalesChannelId { get; set; }
        public string OfficeContact { get; set; }
        public string OfficePhone { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string StateCode { get; set; }
        public string ZipCode { get; set; }
    
        public virtual SalesChannel SalesChannel { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
